/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.51.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * AgentTrafficResponse
 */
@JsonPropertyOrder({
  AgentTrafficResponse.JSON_PROPERTY_PROJECT_ID,
  AgentTrafficResponse.JSON_PROPERTY_FROM,
  AgentTrafficResponse.JSON_PROPERTY_TO,
  AgentTrafficResponse.JSON_PROPERTY_GROUP_BY,
  AgentTrafficResponse.JSON_PROPERTY_GRANULARITY,
  AgentTrafficResponse.JSON_PROPERTY_TOTALS,
  AgentTrafficResponse.JSON_PROPERTY_TIMESERIES,
  AgentTrafficResponse.JSON_PROPERTY_REQUEST_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AgentTrafficResponse {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nullable
  private LocalDate from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nullable
  private LocalDate to;

  /**
   * Gets or Sets groupBy
   */
  public enum GroupByEnum {
    BOT(String.valueOf("bot")),
    
    COMPANY(String.valueOf("company"));

    private String value;

    GroupByEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GroupByEnum fromValue(String value) {
      for (GroupByEnum b : GroupByEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GROUP_BY = "group_by";
  @javax.annotation.Nullable
  private GroupByEnum groupBy;

  /**
   * Gets or Sets granularity
   */
  public enum GranularityEnum {
    DAY(String.valueOf("day")),
    
    WEEK(String.valueOf("week")),
    
    MONTH(String.valueOf("month"));

    private String value;

    GranularityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GranularityEnum fromValue(String value) {
      for (GranularityEnum b : GranularityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GRANULARITY = "granularity";
  @javax.annotation.Nullable
  private GranularityEnum granularity;

  public static final String JSON_PROPERTY_TOTALS = "totals";
  @javax.annotation.Nullable
  private Map<String, Integer> totals = new HashMap<>();

  public static final String JSON_PROPERTY_TIMESERIES = "timeseries";
  @javax.annotation.Nullable
  private Map<String, Map<String, Integer>> timeseries = new HashMap<>();

  public static final String JSON_PROPERTY_REQUEST_ID = "request_id";
  @javax.annotation.Nullable
  private String requestId;

  public AgentTrafficResponse() { 
  }

  public AgentTrafficResponse projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public AgentTrafficResponse from(@javax.annotation.Nullable LocalDate from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrom(@javax.annotation.Nullable LocalDate from) {
    this.from = from;
  }


  public AgentTrafficResponse to(@javax.annotation.Nullable LocalDate to) {
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTo(@javax.annotation.Nullable LocalDate to) {
    this.to = to;
  }


  public AgentTrafficResponse groupBy(@javax.annotation.Nullable GroupByEnum groupBy) {
    this.groupBy = groupBy;
    return this;
  }

  /**
   * Get groupBy
   * @return groupBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GroupByEnum getGroupBy() {
    return groupBy;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupBy(@javax.annotation.Nullable GroupByEnum groupBy) {
    this.groupBy = groupBy;
  }


  public AgentTrafficResponse granularity(@javax.annotation.Nullable GranularityEnum granularity) {
    this.granularity = granularity;
    return this;
  }

  /**
   * Get granularity
   * @return granularity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANULARITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GranularityEnum getGranularity() {
    return granularity;
  }


  @JsonProperty(value = JSON_PROPERTY_GRANULARITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGranularity(@javax.annotation.Nullable GranularityEnum granularity) {
    this.granularity = granularity;
  }


  public AgentTrafficResponse totals(@javax.annotation.Nullable Map<String, Integer> totals) {
    this.totals = totals;
    return this;
  }

  public AgentTrafficResponse putTotalsItem(String key, Integer totalsItem) {
    if (this.totals == null) {
      this.totals = new HashMap<>();
    }
    this.totals.put(key, totalsItem);
    return this;
  }

  /**
   * Get totals
   * @return totals
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Integer> getTotals() {
    return totals;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotals(@javax.annotation.Nullable Map<String, Integer> totals) {
    this.totals = totals;
  }


  public AgentTrafficResponse timeseries(@javax.annotation.Nullable Map<String, Map<String, Integer>> timeseries) {
    this.timeseries = timeseries;
    return this;
  }

  public AgentTrafficResponse putTimeseriesItem(String key, Map<String, Integer> timeseriesItem) {
    if (this.timeseries == null) {
      this.timeseries = new HashMap<>();
    }
    this.timeseries.put(key, timeseriesItem);
    return this;
  }

  /**
   * Get timeseries
   * @return timeseries
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Map<String, Integer>> getTimeseries() {
    return timeseries;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeseries(@javax.annotation.Nullable Map<String, Map<String, Integer>> timeseries) {
    this.timeseries = timeseries;
  }


  public AgentTrafficResponse requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  /**
   * Return true if this AgentTrafficResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentTrafficResponse agentTrafficResponse = (AgentTrafficResponse) o;
    return Objects.equals(this.projectId, agentTrafficResponse.projectId) &&
        Objects.equals(this.from, agentTrafficResponse.from) &&
        Objects.equals(this.to, agentTrafficResponse.to) &&
        Objects.equals(this.groupBy, agentTrafficResponse.groupBy) &&
        Objects.equals(this.granularity, agentTrafficResponse.granularity) &&
        Objects.equals(this.totals, agentTrafficResponse.totals) &&
        Objects.equals(this.timeseries, agentTrafficResponse.timeseries) &&
        Objects.equals(this.requestId, agentTrafficResponse.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, from, to, groupBy, granularity, totals, timeseries, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentTrafficResponse {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    groupBy: ").append(toIndentedString(groupBy)).append("\n");
    sb.append("    granularity: ").append(toIndentedString(granularity)).append("\n");
    sb.append("    totals: ").append(toIndentedString(totals)).append("\n");
    sb.append("    timeseries: ").append(toIndentedString(timeseries)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTo()))));
    }

    // add `group_by` to the URL query string
    if (getGroupBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgroup_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGroupBy()))));
    }

    // add `granularity` to the URL query string
    if (getGranularity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgranularity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGranularity()))));
    }

    // add `totals` to the URL query string
    if (getTotals() != null) {
      for (String _key : getTotals().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stotals%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getTotals().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getTotals().get(_key)))));
      }
    }

    // add `timeseries` to the URL query string
    if (getTimeseries() != null) {
      for (String _key : getTimeseries().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stimeseries%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getTimeseries().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getTimeseries().get(_key)))));
      }
    }

    // add `request_id` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequest_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    return joiner.toString();
  }
}

