/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.AiOrdersResponseBySourceInner;
import ai.llmpulse.sdk.model.AiOrdersResponseSeriesInner;
import ai.llmpulse.sdk.model.AiOrdersResponseTotals;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * AiOrdersResponse
 */
@JsonPropertyOrder({
  AiOrdersResponse.JSON_PROPERTY_PROJECT_ID,
  AiOrdersResponse.JSON_PROPERTY_PLATFORM,
  AiOrdersResponse.JSON_PROPERTY_CURRENCY,
  AiOrdersResponse.JSON_PROPERTY_FROM,
  AiOrdersResponse.JSON_PROPERTY_TO,
  AiOrdersResponse.JSON_PROPERTY_TOTALS,
  AiOrdersResponse.JSON_PROPERTY_BY_SOURCE,
  AiOrdersResponse.JSON_PROPERTY_SERIES,
  AiOrdersResponse.JSON_PROPERTY_REQUEST_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AiOrdersResponse {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nonnull
  private Integer projectId;

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nonnull
  private String platform;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private LocalDate from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nonnull
  private LocalDate to;

  public static final String JSON_PROPERTY_TOTALS = "totals";
  @javax.annotation.Nonnull
  private AiOrdersResponseTotals totals;

  public static final String JSON_PROPERTY_BY_SOURCE = "by_source";
  @javax.annotation.Nonnull
  private List<AiOrdersResponseBySourceInner> bySource = new ArrayList<>();

  public static final String JSON_PROPERTY_SERIES = "series";
  @javax.annotation.Nonnull
  private List<AiOrdersResponseSeriesInner> series = new ArrayList<>();

  public static final String JSON_PROPERTY_REQUEST_ID = "request_id";
  @javax.annotation.Nonnull
  private String requestId;

  public AiOrdersResponse() { 
  }

  public AiOrdersResponse projectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
  }


  public AiOrdersResponse platform(@javax.annotation.Nonnull String platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlatform(@javax.annotation.Nonnull String platform) {
    this.platform = platform;
  }


  public AiOrdersResponse currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * ISO 4217 code of the most recent stored day; null when the window holds no stored order
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public AiOrdersResponse from(@javax.annotation.Nonnull LocalDate from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LocalDate getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull LocalDate from) {
    this.from = from;
  }


  public AiOrdersResponse to(@javax.annotation.Nonnull LocalDate to) {
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LocalDate getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@javax.annotation.Nonnull LocalDate to) {
    this.to = to;
  }


  public AiOrdersResponse totals(@javax.annotation.Nonnull AiOrdersResponseTotals totals) {
    this.totals = totals;
    return this;
  }

  /**
   * Get totals
   * @return totals
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTALS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AiOrdersResponseTotals getTotals() {
    return totals;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTALS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotals(@javax.annotation.Nonnull AiOrdersResponseTotals totals) {
    this.totals = totals;
  }


  public AiOrdersResponse bySource(@javax.annotation.Nonnull List<AiOrdersResponseBySourceInner> bySource) {
    this.bySource = bySource;
    return this;
  }

  public AiOrdersResponse addBySourceItem(AiOrdersResponseBySourceInner bySourceItem) {
    if (this.bySource == null) {
      this.bySource = new ArrayList<>();
    }
    this.bySource.add(bySourceItem);
    return this;
  }

  /**
   * One row per AI assistant, highest revenue first
   * @return bySource
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<AiOrdersResponseBySourceInner> getBySource() {
    return bySource;
  }


  @JsonProperty(value = JSON_PROPERTY_BY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBySource(@javax.annotation.Nonnull List<AiOrdersResponseBySourceInner> bySource) {
    this.bySource = bySource;
  }


  public AiOrdersResponse series(@javax.annotation.Nonnull List<AiOrdersResponseSeriesInner> series) {
    this.series = series;
    return this;
  }

  public AiOrdersResponse addSeriesItem(AiOrdersResponseSeriesInner seriesItem) {
    if (this.series == null) {
      this.series = new ArrayList<>();
    }
    this.series.add(seriesItem);
    return this;
  }

  /**
   * Days that have stored orders, oldest first
   * @return series
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<AiOrdersResponseSeriesInner> getSeries() {
    return series;
  }


  @JsonProperty(value = JSON_PROPERTY_SERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeries(@javax.annotation.Nonnull List<AiOrdersResponseSeriesInner> series) {
    this.series = series;
  }


  public AiOrdersResponse requestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
  }


  /**
   * Return true if this AiOrdersResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiOrdersResponse aiOrdersResponse = (AiOrdersResponse) o;
    return Objects.equals(this.projectId, aiOrdersResponse.projectId) &&
        Objects.equals(this.platform, aiOrdersResponse.platform) &&
        Objects.equals(this.currency, aiOrdersResponse.currency) &&
        Objects.equals(this.from, aiOrdersResponse.from) &&
        Objects.equals(this.to, aiOrdersResponse.to) &&
        Objects.equals(this.totals, aiOrdersResponse.totals) &&
        Objects.equals(this.bySource, aiOrdersResponse.bySource) &&
        Objects.equals(this.series, aiOrdersResponse.series) &&
        Objects.equals(this.requestId, aiOrdersResponse.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, platform, currency, from, to, totals, bySource, series, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiOrdersResponse {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    totals: ").append(toIndentedString(totals)).append("\n");
    sb.append("    bySource: ").append(toIndentedString(bySource)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTo()))));
    }

    // add `totals` to the URL query string
    if (getTotals() != null) {
      joiner.add(getTotals().toUrlQueryString(prefix + "totals" + suffix));
    }

    // add `by_source` to the URL query string
    if (getBySource() != null) {
      for (int i = 0; i < getBySource().size(); i++) {
        if (getBySource().get(i) != null) {
          joiner.add(getBySource().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sby_source%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `series` to the URL query string
    if (getSeries() != null) {
      for (int i = 0; i < getSeries().size(); i++) {
        if (getSeries().get(i) != null) {
          joiner.add(getSeries().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sseries%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `request_id` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequest_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    return joiner.toString();
  }
}

