/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * CatalogPromptSuggestionIdsRequest
 */
@JsonPropertyOrder({
  CatalogPromptSuggestionIdsRequest.JSON_PROPERTY_PROJECT_ID,
  CatalogPromptSuggestionIdsRequest.JSON_PROPERTY_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CatalogPromptSuggestionIdsRequest {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nonnull
  private Integer projectId;

  public static final String JSON_PROPERTY_IDS = "ids";
  @javax.annotation.Nonnull
  private List<Integer> ids = new ArrayList<>();

  public CatalogPromptSuggestionIdsRequest() { 
  }

  public CatalogPromptSuggestionIdsRequest projectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
  }


  public CatalogPromptSuggestionIdsRequest ids(@javax.annotation.Nonnull List<Integer> ids) {
    this.ids = ids;
    return this;
  }

  public CatalogPromptSuggestionIdsRequest addIdsItem(Integer idsItem) {
    if (this.ids == null) {
      this.ids = new ArrayList<>();
    }
    this.ids.add(idsItem);
    return this;
  }

  /**
   * Get ids
   * @return ids
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Integer> getIds() {
    return ids;
  }


  @JsonProperty(value = JSON_PROPERTY_IDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIds(@javax.annotation.Nonnull List<Integer> ids) {
    this.ids = ids;
  }


  /**
   * Return true if this CatalogPromptSuggestionIdsRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogPromptSuggestionIdsRequest catalogPromptSuggestionIdsRequest = (CatalogPromptSuggestionIdsRequest) o;
    return Objects.equals(this.projectId, catalogPromptSuggestionIdsRequest.projectId) &&
        Objects.equals(this.ids, catalogPromptSuggestionIdsRequest.ids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, ids);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogPromptSuggestionIdsRequest {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `ids` to the URL query string
    if (getIds() != null) {
      for (int i = 0; i < getIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getIds().get(i)))));
      }
    }

    return joiner.toString();
  }
}

