/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * CompetitorDetails
 */
@JsonPropertyOrder({
  CompetitorDetails.JSON_PROPERTY_ID,
  CompetitorDetails.JSON_PROPERTY_PROJECT_ID,
  CompetitorDetails.JSON_PROPERTY_BRAND_NAME,
  CompetitorDetails.JSON_PROPERTY_DOMAIN,
  CompetitorDetails.JSON_PROPERTY_MATCHING_NAMES,
  CompetitorDetails.JSON_PROPERTY_GOOGLE_PLAY_ID,
  CompetitorDetails.JSON_PROPERTY_APP_STORE_ID,
  CompetitorDetails.JSON_PROPERTY_COLOR,
  CompetitorDetails.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CompetitorDetails {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_BRAND_NAME = "brand_name";
  @javax.annotation.Nullable
  private String brandName;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nullable
  private String domain;

  public static final String JSON_PROPERTY_MATCHING_NAMES = "matching_names";
  private JsonNullable<List<String>> matchingNames = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_GOOGLE_PLAY_ID = "google_play_id";
  private JsonNullable<String> googlePlayId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_APP_STORE_ID = "app_store_id";
  private JsonNullable<String> appStoreId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COLOR = "color";
  private JsonNullable<String> color = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public CompetitorDetails() { 
  }

  public CompetitorDetails id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public CompetitorDetails projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public CompetitorDetails brandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Get brandName
   * @return brandName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRAND_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBrandName() {
    return brandName;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
  }


  public CompetitorDetails domain(@javax.annotation.Nullable String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(@javax.annotation.Nullable String domain) {
    this.domain = domain;
  }


  public CompetitorDetails matchingNames(@javax.annotation.Nullable List<String> matchingNames) {
    this.matchingNames = JsonNullable.<List<String>>of(matchingNames);
    return this;
  }

  public CompetitorDetails addMatchingNamesItem(String matchingNamesItem) {
    if (this.matchingNames == null || !this.matchingNames.isPresent()) {
      this.matchingNames = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.matchingNames.get().add(matchingNamesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get matchingNames
   * @return matchingNames
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<String> getMatchingNames() {
        return matchingNames.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MATCHING_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getMatchingNames_JsonNullable() {
    return matchingNames;
  }
  
  @JsonProperty(JSON_PROPERTY_MATCHING_NAMES)
  public void setMatchingNames_JsonNullable(JsonNullable<List<String>> matchingNames) {
    this.matchingNames = matchingNames;
  }

  public void setMatchingNames(@javax.annotation.Nullable List<String> matchingNames) {
    this.matchingNames = JsonNullable.<List<String>>of(matchingNames);
  }


  public CompetitorDetails googlePlayId(@javax.annotation.Nullable String googlePlayId) {
    this.googlePlayId = JsonNullable.<String>of(googlePlayId);
    return this;
  }

  /**
   * Get googlePlayId
   * @return googlePlayId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGooglePlayId() {
        return googlePlayId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GOOGLE_PLAY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGooglePlayId_JsonNullable() {
    return googlePlayId;
  }
  
  @JsonProperty(JSON_PROPERTY_GOOGLE_PLAY_ID)
  public void setGooglePlayId_JsonNullable(JsonNullable<String> googlePlayId) {
    this.googlePlayId = googlePlayId;
  }

  public void setGooglePlayId(@javax.annotation.Nullable String googlePlayId) {
    this.googlePlayId = JsonNullable.<String>of(googlePlayId);
  }


  public CompetitorDetails appStoreId(@javax.annotation.Nullable String appStoreId) {
    this.appStoreId = JsonNullable.<String>of(appStoreId);
    return this;
  }

  /**
   * Get appStoreId
   * @return appStoreId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAppStoreId() {
        return appStoreId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_APP_STORE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAppStoreId_JsonNullable() {
    return appStoreId;
  }
  
  @JsonProperty(JSON_PROPERTY_APP_STORE_ID)
  public void setAppStoreId_JsonNullable(JsonNullable<String> appStoreId) {
    this.appStoreId = appStoreId;
  }

  public void setAppStoreId(@javax.annotation.Nullable String appStoreId) {
    this.appStoreId = JsonNullable.<String>of(appStoreId);
  }


  public CompetitorDetails color(@javax.annotation.Nullable String color) {
    this.color = JsonNullable.<String>of(color);
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getColor() {
        return color.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getColor_JsonNullable() {
    return color;
  }
  
  @JsonProperty(JSON_PROPERTY_COLOR)
  public void setColor_JsonNullable(JsonNullable<String> color) {
    this.color = color;
  }

  public void setColor(@javax.annotation.Nullable String color) {
    this.color = JsonNullable.<String>of(color);
  }


  public CompetitorDetails createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this CompetitorDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitorDetails competitorDetails = (CompetitorDetails) o;
    return Objects.equals(this.id, competitorDetails.id) &&
        Objects.equals(this.projectId, competitorDetails.projectId) &&
        Objects.equals(this.brandName, competitorDetails.brandName) &&
        Objects.equals(this.domain, competitorDetails.domain) &&
        equalsNullable(this.matchingNames, competitorDetails.matchingNames) &&
        equalsNullable(this.googlePlayId, competitorDetails.googlePlayId) &&
        equalsNullable(this.appStoreId, competitorDetails.appStoreId) &&
        equalsNullable(this.color, competitorDetails.color) &&
        Objects.equals(this.createdAt, competitorDetails.createdAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, brandName, domain, hashCodeNullable(matchingNames), hashCodeNullable(googlePlayId), hashCodeNullable(appStoreId), hashCodeNullable(color), createdAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitorDetails {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    matchingNames: ").append(toIndentedString(matchingNames)).append("\n");
    sb.append("    googlePlayId: ").append(toIndentedString(googlePlayId)).append("\n");
    sb.append("    appStoreId: ").append(toIndentedString(appStoreId)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `brand_name` to the URL query string
    if (getBrandName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrand_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrandName()))));
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `matching_names` to the URL query string
    if (getMatchingNames() != null) {
      for (int i = 0; i < getMatchingNames().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smatching_names%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getMatchingNames().get(i)))));
      }
    }

    // add `google_play_id` to the URL query string
    if (getGooglePlayId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgoogle_play_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGooglePlayId()))));
    }

    // add `app_store_id` to the URL query string
    if (getAppStoreId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapp_store_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAppStoreId()))));
    }

    // add `color` to the URL query string
    if (getColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColor()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

