/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * CreateWebhookRequest
 */
@JsonPropertyOrder({
  CreateWebhookRequest.JSON_PROPERTY_PROJECT_ID,
  CreateWebhookRequest.JSON_PROPERTY_EVENT_TYPE,
  CreateWebhookRequest.JSON_PROPERTY_TARGET_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CreateWebhookRequest {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nonnull
  private Integer projectId;

  /**
   * Gets or Sets eventType
   */
  public enum EventTypeEnum {
    MENTION_CREATED(String.valueOf("mention.created")),
    
    COMPETITOR_MENTION_CREATED(String.valueOf("competitor_mention.created")),
    
    CITATION_CREATED(String.valueOf("citation.created")),
    
    PROMPT_EXECUTION_COMPLETED(String.valueOf("prompt_execution.completed")),
    
    SENTIMENT_NEGATIVE_DETECTED(String.valueOf("sentiment.negative_detected")),
    
    RECOMMENDATION_COMPLETED(String.valueOf("recommendation.completed")),
    
    INTELLIGENCE_TASK_COMPLETED(String.valueOf("intelligence_task.completed")),
    
    INTELLIGENCE_TASK_UPDATED(String.valueOf("intelligence_task.updated"));

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
  @javax.annotation.Nonnull
  private EventTypeEnum eventType;

  public static final String JSON_PROPERTY_TARGET_URL = "target_url";
  @javax.annotation.Nonnull
  private String targetUrl;

  public CreateWebhookRequest() { 
  }

  public CreateWebhookRequest projectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
  }


  public CreateWebhookRequest eventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public CreateWebhookRequest targetUrl(@javax.annotation.Nonnull String targetUrl) {
    this.targetUrl = targetUrl;
    return this;
  }

  /**
   * Public HTTPS URL that will receive signed event payloads
   * @return targetUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TARGET_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTargetUrl() {
    return targetUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTargetUrl(@javax.annotation.Nonnull String targetUrl) {
    this.targetUrl = targetUrl;
  }


  /**
   * Return true if this createWebhook_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWebhookRequest createWebhookRequest = (CreateWebhookRequest) o;
    return Objects.equals(this.projectId, createWebhookRequest.projectId) &&
        Objects.equals(this.eventType, createWebhookRequest.eventType) &&
        Objects.equals(this.targetUrl, createWebhookRequest.targetUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, eventType, targetUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWebhookRequest {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `event_type` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `target_url` to the URL query string
    if (getTargetUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%starget_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetUrl()))));
    }

    return joiner.toString();
  }
}

