/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * CreateWebhook201Response
 */
@JsonPropertyOrder({
  CreateWebhook201Response.JSON_PROPERTY_ID,
  CreateWebhook201Response.JSON_PROPERTY_PROJECT_ID,
  CreateWebhook201Response.JSON_PROPERTY_EVENT_TYPE,
  CreateWebhook201Response.JSON_PROPERTY_TARGET_URL,
  CreateWebhook201Response.JSON_PROPERTY_DISABLED,
  CreateWebhook201Response.JSON_PROPERTY_FAILURE_COUNT,
  CreateWebhook201Response.JSON_PROPERTY_LAST_DELIVERED_AT,
  CreateWebhook201Response.JSON_PROPERTY_CREATED_AT,
  CreateWebhook201Response.JSON_PROPERTY_SECRET,
  CreateWebhook201Response.JSON_PROPERTY_REQUEST_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CreateWebhook201Response {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  /**
   * Gets or Sets eventType
   */
  public enum EventTypeEnum {
    MENTION_CREATED(String.valueOf("mention.created")),
    
    COMPETITOR_MENTION_CREATED(String.valueOf("competitor_mention.created")),
    
    CITATION_CREATED(String.valueOf("citation.created")),
    
    PROMPT_EXECUTION_COMPLETED(String.valueOf("prompt_execution.completed")),
    
    SENTIMENT_NEGATIVE_DETECTED(String.valueOf("sentiment.negative_detected")),
    
    RECOMMENDATION_COMPLETED(String.valueOf("recommendation.completed")),
    
    INTELLIGENCE_TASK_COMPLETED(String.valueOf("intelligence_task.completed")),
    
    INTELLIGENCE_TASK_UPDATED(String.valueOf("intelligence_task.updated")),
    
    GEO_AUDIT_RUN_COMPLETED(String.valueOf("geo_audit_run.completed")),
    
    GEO_AUDIT_ALERT_TRIGGERED(String.valueOf("geo_audit_alert.triggered"));

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
  @javax.annotation.Nullable
  private EventTypeEnum eventType;

  public static final String JSON_PROPERTY_TARGET_URL = "target_url";
  @javax.annotation.Nullable
  private String targetUrl;

  public static final String JSON_PROPERTY_DISABLED = "disabled";
  @javax.annotation.Nullable
  private Boolean disabled;

  public static final String JSON_PROPERTY_FAILURE_COUNT = "failure_count";
  @javax.annotation.Nullable
  private Integer failureCount;

  public static final String JSON_PROPERTY_LAST_DELIVERED_AT = "last_delivered_at";
  private JsonNullable<OffsetDateTime> lastDeliveredAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @javax.annotation.Nullable
  private String secret;

  public static final String JSON_PROPERTY_REQUEST_ID = "request_id";
  @javax.annotation.Nullable
  private String requestId;

  public CreateWebhook201Response() { 
  }

  public CreateWebhook201Response id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public CreateWebhook201Response projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public CreateWebhook201Response eventType(@javax.annotation.Nullable EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@javax.annotation.Nullable EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public CreateWebhook201Response targetUrl(@javax.annotation.Nullable String targetUrl) {
    this.targetUrl = targetUrl;
    return this;
  }

  /**
   * Get targetUrl
   * @return targetUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTargetUrl() {
    return targetUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetUrl(@javax.annotation.Nullable String targetUrl) {
    this.targetUrl = targetUrl;
  }


  public CreateWebhook201Response disabled(@javax.annotation.Nullable Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

  /**
   * Get disabled
   * @return disabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDisabled() {
    return disabled;
  }


  @JsonProperty(value = JSON_PROPERTY_DISABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisabled(@javax.annotation.Nullable Boolean disabled) {
    this.disabled = disabled;
  }


  public CreateWebhook201Response failureCount(@javax.annotation.Nullable Integer failureCount) {
    this.failureCount = failureCount;
    return this;
  }

  /**
   * Get failureCount
   * @return failureCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFailureCount() {
    return failureCount;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureCount(@javax.annotation.Nullable Integer failureCount) {
    this.failureCount = failureCount;
  }


  public CreateWebhook201Response lastDeliveredAt(@javax.annotation.Nullable OffsetDateTime lastDeliveredAt) {
    this.lastDeliveredAt = JsonNullable.<OffsetDateTime>of(lastDeliveredAt);
    return this;
  }

  /**
   * Get lastDeliveredAt
   * @return lastDeliveredAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getLastDeliveredAt() {
        return lastDeliveredAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_DELIVERED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLastDeliveredAt_JsonNullable() {
    return lastDeliveredAt;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_DELIVERED_AT)
  public void setLastDeliveredAt_JsonNullable(JsonNullable<OffsetDateTime> lastDeliveredAt) {
    this.lastDeliveredAt = lastDeliveredAt;
  }

  public void setLastDeliveredAt(@javax.annotation.Nullable OffsetDateTime lastDeliveredAt) {
    this.lastDeliveredAt = JsonNullable.<OffsetDateTime>of(lastDeliveredAt);
  }


  public CreateWebhook201Response createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CreateWebhook201Response secret(@javax.annotation.Nullable String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * HMAC signing secret (whsec_...). Only returned on create.
   * @return secret
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@javax.annotation.Nullable String secret) {
    this.secret = secret;
  }


  public CreateWebhook201Response requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  /**
   * Return true if this createWebhook_201_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWebhook201Response createWebhook201Response = (CreateWebhook201Response) o;
    return Objects.equals(this.id, createWebhook201Response.id) &&
        Objects.equals(this.projectId, createWebhook201Response.projectId) &&
        Objects.equals(this.eventType, createWebhook201Response.eventType) &&
        Objects.equals(this.targetUrl, createWebhook201Response.targetUrl) &&
        Objects.equals(this.disabled, createWebhook201Response.disabled) &&
        Objects.equals(this.failureCount, createWebhook201Response.failureCount) &&
        equalsNullable(this.lastDeliveredAt, createWebhook201Response.lastDeliveredAt) &&
        Objects.equals(this.createdAt, createWebhook201Response.createdAt) &&
        Objects.equals(this.secret, createWebhook201Response.secret) &&
        Objects.equals(this.requestId, createWebhook201Response.requestId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, eventType, targetUrl, disabled, failureCount, hashCodeNullable(lastDeliveredAt), createdAt, secret, requestId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWebhook201Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    failureCount: ").append(toIndentedString(failureCount)).append("\n");
    sb.append("    lastDeliveredAt: ").append(toIndentedString(lastDeliveredAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `event_type` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `target_url` to the URL query string
    if (getTargetUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%starget_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetUrl()))));
    }

    // add `disabled` to the URL query string
    if (getDisabled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisabled()))));
    }

    // add `failure_count` to the URL query string
    if (getFailureCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailure_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureCount()))));
    }

    // add `last_delivered_at` to the URL query string
    if (getLastDeliveredAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_delivered_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastDeliveredAt()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `secret` to the URL query string
    if (getSecret() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssecret%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSecret()))));
    }

    // add `request_id` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequest_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    return joiner.toString();
  }
}

