/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * GeoAuditCreateRequest
 */
@JsonPropertyOrder({
  GeoAuditCreateRequest.JSON_PROPERTY_PROJECT_ID,
  GeoAuditCreateRequest.JSON_PROPERTY_TARGET,
  GeoAuditCreateRequest.JSON_PROPERTY_AUDIT_TYPES,
  GeoAuditCreateRequest.JSON_PROPERTY_CADENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GeoAuditCreateRequest {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nonnull
  private Integer projectId;

  public static final String JSON_PROPERTY_TARGET = "target";
  @javax.annotation.Nonnull
  private String target;

  /**
   * Gets or Sets auditTypes
   */
  public enum AuditTypesEnum {
    AGENT_READINESS(String.valueOf("agent_readiness")),
    
    ROBOTS_TXT(String.valueOf("robots_txt")),
    
    CRAWLABILITY(String.valueOf("crawlability")),
    
    SCHEMA(String.valueOf("schema")),
    
    CONTENT_READINESS(String.valueOf("content_readiness")),
    
    DISCOVERABILITY(String.valueOf("discoverability")),
    
    SITE_STRUCTURE(String.valueOf("site_structure"));

    private String value;

    AuditTypesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuditTypesEnum fromValue(String value) {
      for (AuditTypesEnum b : AuditTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_AUDIT_TYPES = "audit_types";
  @javax.annotation.Nonnull
  private List<AuditTypesEnum> auditTypes = new ArrayList<>();

  /**
   * once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits
   */
  public enum CadenceEnum {
    ONCE(String.valueOf("once")),
    
    WEEKLY(String.valueOf("weekly")),
    
    MONTHLY(String.valueOf("monthly"));

    private String value;

    CadenceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CadenceEnum fromValue(String value) {
      for (CadenceEnum b : CadenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CADENCE = "cadence";
  @javax.annotation.Nullable
  private CadenceEnum cadence;

  public GeoAuditCreateRequest() { 
  }

  public GeoAuditCreateRequest projectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
  }


  public GeoAuditCreateRequest target(@javax.annotation.Nonnull String target) {
    this.target = target;
    return this;
  }

  /**
   * The domain (site-wide types) or page URL to audit
   * @return target
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TARGET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTarget() {
    return target;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTarget(@javax.annotation.Nonnull String target) {
    this.target = target;
  }


  public GeoAuditCreateRequest auditTypes(@javax.annotation.Nonnull List<AuditTypesEnum> auditTypes) {
    this.auditTypes = auditTypes;
    return this;
  }

  public GeoAuditCreateRequest addAuditTypesItem(AuditTypesEnum auditTypesItem) {
    if (this.auditTypes == null) {
      this.auditTypes = new ArrayList<>();
    }
    this.auditTypes.add(auditTypesItem);
    return this;
  }

  /**
   * One or more audit types; each becomes its own audit and starts its first run
   * @return auditTypes
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUDIT_TYPES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<AuditTypesEnum> getAuditTypes() {
    return auditTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIT_TYPES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuditTypes(@javax.annotation.Nonnull List<AuditTypesEnum> auditTypes) {
    this.auditTypes = auditTypes;
  }


  public GeoAuditCreateRequest cadence(@javax.annotation.Nullable CadenceEnum cadence) {
    this.cadence = cadence;
    return this;
  }

  /**
   * once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits
   * @return cadence
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CADENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CadenceEnum getCadence() {
    return cadence;
  }


  @JsonProperty(value = JSON_PROPERTY_CADENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCadence(@javax.annotation.Nullable CadenceEnum cadence) {
    this.cadence = cadence;
  }


  /**
   * Return true if this GeoAuditCreateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoAuditCreateRequest geoAuditCreateRequest = (GeoAuditCreateRequest) o;
    return Objects.equals(this.projectId, geoAuditCreateRequest.projectId) &&
        Objects.equals(this.target, geoAuditCreateRequest.target) &&
        Objects.equals(this.auditTypes, geoAuditCreateRequest.auditTypes) &&
        Objects.equals(this.cadence, geoAuditCreateRequest.cadence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, target, auditTypes, cadence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoAuditCreateRequest {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    auditTypes: ").append(toIndentedString(auditTypes)).append("\n");
    sb.append("    cadence: ").append(toIndentedString(cadence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `target` to the URL query string
    if (getTarget() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%starget%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTarget()))));
    }

    // add `audit_types` to the URL query string
    if (getAuditTypes() != null) {
      for (int i = 0; i < getAuditTypes().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%saudit_types%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAuditTypes().get(i)))));
      }
    }

    // add `cadence` to the URL query string
    if (getCadence() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scadence%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCadence()))));
    }

    return joiner.toString();
  }
}

