/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * GeoAlertEventsInner
 */
@JsonPropertyOrder({
  GeoAlertEventsInner.JSON_PROPERTY_KIND,
  GeoAlertEventsInner.JSON_PROPERTY_CHECK_KEY,
  GeoAlertEventsInner.JSON_PROPERTY_SUBJECT_KEY,
  GeoAlertEventsInner.JSON_PROPERTY_SEVERITY,
  GeoAlertEventsInner.JSON_PROPERTY_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GeoAlertEventsInner {
  /**
   * Gets or Sets kind
   */
  public enum KindEnum {
    NEW_CRITICAL(String.valueOf("new_critical")),
    
    REGRESSION(String.valueOf("regression")),
    
    RECOVERED(String.valueOf("recovered")),
    
    SCORE_DROP(String.valueOf("score_drop")),
    
    UNREACHABLE(String.valueOf("unreachable")),
    
    PAUSED(String.valueOf("paused"));

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nullable
  private KindEnum kind;

  public static final String JSON_PROPERTY_CHECK_KEY = "check_key";
  private JsonNullable<String> checkKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SUBJECT_KEY = "subject_key";
  private JsonNullable<String> subjectKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  @javax.annotation.Nullable
  private String severity;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public GeoAlertEventsInner() { 
  }

  public GeoAlertEventsInner kind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
  }


  public GeoAlertEventsInner checkKey(@javax.annotation.Nullable String checkKey) {
    this.checkKey = JsonNullable.<String>of(checkKey);
    return this;
  }

  /**
   * Get checkKey
   * @return checkKey
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCheckKey() {
        return checkKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CHECK_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCheckKey_JsonNullable() {
    return checkKey;
  }
  
  @JsonProperty(JSON_PROPERTY_CHECK_KEY)
  public void setCheckKey_JsonNullable(JsonNullable<String> checkKey) {
    this.checkKey = checkKey;
  }

  public void setCheckKey(@javax.annotation.Nullable String checkKey) {
    this.checkKey = JsonNullable.<String>of(checkKey);
  }


  public GeoAlertEventsInner subjectKey(@javax.annotation.Nullable String subjectKey) {
    this.subjectKey = JsonNullable.<String>of(subjectKey);
    return this;
  }

  /**
   * Get subjectKey
   * @return subjectKey
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getSubjectKey() {
        return subjectKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUBJECT_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSubjectKey_JsonNullable() {
    return subjectKey;
  }
  
  @JsonProperty(JSON_PROPERTY_SUBJECT_KEY)
  public void setSubjectKey_JsonNullable(JsonNullable<String> subjectKey) {
    this.subjectKey = subjectKey;
  }

  public void setSubjectKey(@javax.annotation.Nullable String subjectKey) {
    this.subjectKey = JsonNullable.<String>of(subjectKey);
  }


  public GeoAlertEventsInner severity(@javax.annotation.Nullable String severity) {
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSeverity() {
    return severity;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverity(@javax.annotation.Nullable String severity) {
    this.severity = severity;
  }


  public GeoAlertEventsInner message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  /**
   * Return true if this GeoAlert_events_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoAlertEventsInner geoAlertEventsInner = (GeoAlertEventsInner) o;
    return Objects.equals(this.kind, geoAlertEventsInner.kind) &&
        equalsNullable(this.checkKey, geoAlertEventsInner.checkKey) &&
        equalsNullable(this.subjectKey, geoAlertEventsInner.subjectKey) &&
        Objects.equals(this.severity, geoAlertEventsInner.severity) &&
        Objects.equals(this.message, geoAlertEventsInner.message);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, hashCodeNullable(checkKey), hashCodeNullable(subjectKey), severity, message);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoAlertEventsInner {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    checkKey: ").append(toIndentedString(checkKey)).append("\n");
    sb.append("    subjectKey: ").append(toIndentedString(subjectKey)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `check_key` to the URL query string
    if (getCheckKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scheck_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCheckKey()))));
    }

    // add `subject_key` to the URL query string
    if (getSubjectKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubjectKey()))));
    }

    // add `severity` to the URL query string
    if (getSeverity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sseverity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSeverity()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    return joiner.toString();
  }
}

