/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.GeoAuditRun;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * GeoAuditRunList
 */
@JsonPropertyOrder({
  GeoAuditRunList.JSON_PROPERTY_PROJECT_ID,
  GeoAuditRunList.JSON_PROPERTY_PAGE,
  GeoAuditRunList.JSON_PROPERTY_PER_PAGE,
  GeoAuditRunList.JSON_PROPERTY_TOTAL,
  GeoAuditRunList.JSON_PROPERTY_DATA,
  GeoAuditRunList.JSON_PROPERTY_REQUEST_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GeoAuditRunList {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable
  private Integer page;

  public static final String JSON_PROPERTY_PER_PAGE = "per_page";
  @javax.annotation.Nullable
  private Integer perPage;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nullable
  private Integer total;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<GeoAuditRun> data = new ArrayList<>();

  public static final String JSON_PROPERTY_REQUEST_ID = "request_id";
  @javax.annotation.Nullable
  private String requestId;

  public GeoAuditRunList() { 
  }

  public GeoAuditRunList projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public GeoAuditRunList page(@javax.annotation.Nullable Integer page) {
    this.page = page;
    return this;
  }

  /**
   * Get page
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPage() {
    return page;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable Integer page) {
    this.page = page;
  }


  public GeoAuditRunList perPage(@javax.annotation.Nullable Integer perPage) {
    this.perPage = perPage;
    return this;
  }

  /**
   * Get perPage
   * @return perPage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PER_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPerPage() {
    return perPage;
  }


  @JsonProperty(value = JSON_PROPERTY_PER_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerPage(@javax.annotation.Nullable Integer perPage) {
    this.perPage = perPage;
  }


  public GeoAuditRunList total(@javax.annotation.Nullable Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(@javax.annotation.Nullable Integer total) {
    this.total = total;
  }


  public GeoAuditRunList data(@javax.annotation.Nullable List<GeoAuditRun> data) {
    this.data = data;
    return this;
  }

  public GeoAuditRunList addDataItem(GeoAuditRun dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GeoAuditRun> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<GeoAuditRun> data) {
    this.data = data;
  }


  public GeoAuditRunList requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  /**
   * Return true if this GeoAuditRunList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoAuditRunList geoAuditRunList = (GeoAuditRunList) o;
    return Objects.equals(this.projectId, geoAuditRunList.projectId) &&
        Objects.equals(this.page, geoAuditRunList.page) &&
        Objects.equals(this.perPage, geoAuditRunList.perPage) &&
        Objects.equals(this.total, geoAuditRunList.total) &&
        Objects.equals(this.data, geoAuditRunList.data) &&
        Objects.equals(this.requestId, geoAuditRunList.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, page, perPage, total, data, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoAuditRunList {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `page` to the URL query string
    if (getPage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPage()))));
    }

    // add `per_page` to the URL query string
    if (getPerPage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sper_page%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPerPage()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (int i = 0; i < getData().size(); i++) {
        if (getData().get(i) != null) {
          joiner.add(getData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `request_id` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequest_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    return joiner.toString();
  }
}

