/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * GetAccount200ResponseRateLimits
 */
@JsonPropertyOrder({
  GetAccount200ResponseRateLimits.JSON_PROPERTY_REQUESTS_PER_MINUTE,
  GetAccount200ResponseRateLimits.JSON_PROPERTY_WRITE_REQUESTS_PER_MINUTE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GetAccount200ResponseRateLimits {
  public static final String JSON_PROPERTY_REQUESTS_PER_MINUTE = "requests_per_minute";
  @javax.annotation.Nullable
  private Integer requestsPerMinute;

  public static final String JSON_PROPERTY_WRITE_REQUESTS_PER_MINUTE = "write_requests_per_minute";
  @javax.annotation.Nullable
  private Integer writeRequestsPerMinute;

  public GetAccount200ResponseRateLimits() { 
  }

  public GetAccount200ResponseRateLimits requestsPerMinute(@javax.annotation.Nullable Integer requestsPerMinute) {
    this.requestsPerMinute = requestsPerMinute;
    return this;
  }

  /**
   * The ceiling enforced for the API key used on this call, which may be above the 300/min default.
   * @return requestsPerMinute
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUESTS_PER_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRequestsPerMinute() {
    return requestsPerMinute;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUESTS_PER_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestsPerMinute(@javax.annotation.Nullable Integer requestsPerMinute) {
    this.requestsPerMinute = requestsPerMinute;
  }


  public GetAccount200ResponseRateLimits writeRequestsPerMinute(@javax.annotation.Nullable Integer writeRequestsPerMinute) {
    this.writeRequestsPerMinute = writeRequestsPerMinute;
    return this;
  }

  /**
   * Flat ceiling on write requests, the same for every key.
   * @return writeRequestsPerMinute
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WRITE_REQUESTS_PER_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWriteRequestsPerMinute() {
    return writeRequestsPerMinute;
  }


  @JsonProperty(value = JSON_PROPERTY_WRITE_REQUESTS_PER_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWriteRequestsPerMinute(@javax.annotation.Nullable Integer writeRequestsPerMinute) {
    this.writeRequestsPerMinute = writeRequestsPerMinute;
  }


  /**
   * Return true if this getAccount_200_response_rate_limits object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAccount200ResponseRateLimits getAccount200ResponseRateLimits = (GetAccount200ResponseRateLimits) o;
    return Objects.equals(this.requestsPerMinute, getAccount200ResponseRateLimits.requestsPerMinute) &&
        Objects.equals(this.writeRequestsPerMinute, getAccount200ResponseRateLimits.writeRequestsPerMinute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestsPerMinute, writeRequestsPerMinute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAccount200ResponseRateLimits {\n");
    sb.append("    requestsPerMinute: ").append(toIndentedString(requestsPerMinute)).append("\n");
    sb.append("    writeRequestsPerMinute: ").append(toIndentedString(writeRequestsPerMinute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requests_per_minute` to the URL query string
    if (getRequestsPerMinute() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequests_per_minute%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestsPerMinute()))));
    }

    // add `write_requests_per_minute` to the URL query string
    if (getWriteRequestsPerMinute() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swrite_requests_per_minute%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWriteRequestsPerMinute()))));
    }

    return joiner.toString();
  }
}

