/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * MentionRecord
 */
@JsonPropertyOrder({
  MentionRecord.JSON_PROPERTY_ID,
  MentionRecord.JSON_PROPERTY_NAME,
  MentionRecord.JSON_PROPERTY_PROMPT_ID,
  MentionRecord.JSON_PROPERTY_PROMPT_EXECUTION_ID,
  MentionRecord.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class MentionRecord {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_PROMPT_ID = "prompt_id";
  @javax.annotation.Nonnull
  private Integer promptId;

  public static final String JSON_PROPERTY_PROMPT_EXECUTION_ID = "prompt_execution_id";
  @javax.annotation.Nonnull
  private Integer promptExecutionId;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public MentionRecord() { 
  }

  public MentionRecord id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public MentionRecord name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The project&#39;s brand name (its name when no brand name is set)
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public MentionRecord promptId(@javax.annotation.Nonnull Integer promptId) {
    this.promptId = promptId;
    return this;
  }

  /**
   * Get promptId
   * @return promptId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROMPT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getPromptId() {
    return promptId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromptId(@javax.annotation.Nonnull Integer promptId) {
    this.promptId = promptId;
  }


  public MentionRecord promptExecutionId(@javax.annotation.Nonnull Integer promptExecutionId) {
    this.promptExecutionId = promptExecutionId;
    return this;
  }

  /**
   * Get promptExecutionId
   * @return promptExecutionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROMPT_EXECUTION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getPromptExecutionId() {
    return promptExecutionId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPT_EXECUTION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromptExecutionId(@javax.annotation.Nonnull Integer promptExecutionId) {
    this.promptExecutionId = promptExecutionId;
  }


  public MentionRecord createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this MentionRecord object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MentionRecord mentionRecord = (MentionRecord) o;
    return Objects.equals(this.id, mentionRecord.id) &&
        Objects.equals(this.name, mentionRecord.name) &&
        Objects.equals(this.promptId, mentionRecord.promptId) &&
        Objects.equals(this.promptExecutionId, mentionRecord.promptExecutionId) &&
        Objects.equals(this.createdAt, mentionRecord.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, promptId, promptExecutionId, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MentionRecord {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    promptId: ").append(toIndentedString(promptId)).append("\n");
    sb.append("    promptExecutionId: ").append(toIndentedString(promptExecutionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `prompt_id` to the URL query string
    if (getPromptId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprompt_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPromptId()))));
    }

    // add `prompt_execution_id` to the URL query string
    if (getPromptExecutionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprompt_execution_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPromptExecutionId()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

