/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * The filters the response was computed with, as the server resolved them. Each endpoint echoes only the keys it reads; a filter that was not given comes back null (or an empty list).
 */
@JsonPropertyOrder({
  MetricsFiltersEcho.JSON_PROPERTY_METRICS,
  MetricsFiltersEcho.JSON_PROPERTY_GRANULARITY,
  MetricsFiltersEcho.JSON_PROPERTY_MODEL,
  MetricsFiltersEcho.JSON_PROPERTY_COLLECTION_ID,
  MetricsFiltersEcho.JSON_PROPERTY_COLLECTION_IDS,
  MetricsFiltersEcho.JSON_PROPERTY_DOMAINS,
  MetricsFiltersEcho.JSON_PROPERTY_COUNTRY_CODE,
  MetricsFiltersEcho.JSON_PROPERTY_LANGUAGE_CODE,
  MetricsFiltersEcho.JSON_PROPERTY_PROMPT,
  MetricsFiltersEcho.JSON_PROPERTY_PROMPT_TYPE,
  MetricsFiltersEcho.JSON_PROPERTY_BRAND_KIND,
  MetricsFiltersEcho.JSON_PROPERTY_COMPETITORS,
  MetricsFiltersEcho.JSON_PROPERTY_INCLUDE_PROJECT,
  MetricsFiltersEcho.JSON_PROPERTY_QUERY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class MetricsFiltersEcho {
  public static final String JSON_PROPERTY_METRICS = "metrics";
  @javax.annotation.Nullable
  private List<String> metrics = new ArrayList<>();

  public static final String JSON_PROPERTY_GRANULARITY = "granularity";
  @javax.annotation.Nullable
  private String granularity;

  public static final String JSON_PROPERTY_MODEL = "model";
  private JsonNullable<String> model = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private JsonNullable<String> collectionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COLLECTION_IDS = "collection_ids";
  private JsonNullable<List<Integer>> collectionIds = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_DOMAINS = "domains";
  private JsonNullable<List<String>> domains = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  private JsonNullable<String> countryCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LANGUAGE_CODE = "language_code";
  private JsonNullable<String> languageCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROMPT = "prompt";
  private JsonNullable<Integer> prompt = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PROMPT_TYPE = "prompt_type";
  private JsonNullable<String> promptType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BRAND_KIND = "brand_kind";
  private JsonNullable<String> brandKind = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COMPETITORS = "competitors";
  @javax.annotation.Nullable
  private List<Integer> competitors = new ArrayList<>();

  public static final String JSON_PROPERTY_INCLUDE_PROJECT = "include_project";
  @javax.annotation.Nullable
  private Boolean includeProject;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nullable
  private String query;

  public MetricsFiltersEcho() { 
  }

  public MetricsFiltersEcho metrics(@javax.annotation.Nullable List<String> metrics) {
    this.metrics = metrics;
    return this;
  }

  public MetricsFiltersEcho addMetricsItem(String metricsItem) {
    if (this.metrics == null) {
      this.metrics = new ArrayList<>();
    }
    this.metrics.add(metricsItem);
    return this;
  }

  /**
   * Requested metrics after alias resolution (mention_rate is echoed as visibility)
   * @return metrics
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getMetrics() {
    return metrics;
  }


  @JsonProperty(value = JSON_PROPERTY_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetrics(@javax.annotation.Nullable List<String> metrics) {
    this.metrics = metrics;
  }


  public MetricsFiltersEcho granularity(@javax.annotation.Nullable String granularity) {
    this.granularity = granularity;
    return this;
  }

  /**
   * day, week or month
   * @return granularity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANULARITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGranularity() {
    return granularity;
  }


  @JsonProperty(value = JSON_PROPERTY_GRANULARITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGranularity(@javax.annotation.Nullable String granularity) {
    this.granularity = granularity;
  }


  public MetricsFiltersEcho model(@javax.annotation.Nullable String model) {
    this.model = JsonNullable.<String>of(model);
    return this;
  }

  /**
   * The model filter, or null when absent or not enabled for the account
   * @return model
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getModel() {
        return model.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getModel_JsonNullable() {
    return model;
  }
  
  @JsonProperty(JSON_PROPERTY_MODEL)
  public void setModel_JsonNullable(JsonNullable<String> model) {
    this.model = model;
  }

  public void setModel(@javax.annotation.Nullable String model) {
    this.model = JsonNullable.<String>of(model);
  }


  public MetricsFiltersEcho collectionId(@javax.annotation.Nullable String collectionId) {
    this.collectionId = JsonNullable.<String>of(collectionId);
    return this;
  }

  /**
   * The collection_id parameter as sent (one id or a comma-separated list)
   * @return collectionId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCollectionId() {
        return collectionId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COLLECTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCollectionId_JsonNullable() {
    return collectionId;
  }
  
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  public void setCollectionId_JsonNullable(JsonNullable<String> collectionId) {
    this.collectionId = collectionId;
  }

  public void setCollectionId(@javax.annotation.Nullable String collectionId) {
    this.collectionId = JsonNullable.<String>of(collectionId);
  }


  public MetricsFiltersEcho collectionIds(@javax.annotation.Nullable List<Integer> collectionIds) {
    this.collectionIds = JsonNullable.<List<Integer>>of(collectionIds);
    return this;
  }

  public MetricsFiltersEcho addCollectionIdsItem(Integer collectionIdsItem) {
    if (this.collectionIds == null || !this.collectionIds.isPresent()) {
      this.collectionIds = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.collectionIds.get().add(collectionIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get collectionIds
   * @return collectionIds
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<Integer> getCollectionIds() {
        return collectionIds.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COLLECTION_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getCollectionIds_JsonNullable() {
    return collectionIds;
  }
  
  @JsonProperty(JSON_PROPERTY_COLLECTION_IDS)
  public void setCollectionIds_JsonNullable(JsonNullable<List<Integer>> collectionIds) {
    this.collectionIds = collectionIds;
  }

  public void setCollectionIds(@javax.annotation.Nullable List<Integer> collectionIds) {
    this.collectionIds = JsonNullable.<List<Integer>>of(collectionIds);
  }


  public MetricsFiltersEcho domains(@javax.annotation.Nullable List<String> domains) {
    this.domains = JsonNullable.<List<String>>of(domains);
    return this;
  }

  public MetricsFiltersEcho addDomainsItem(String domainsItem) {
    if (this.domains == null || !this.domains.isPresent()) {
      this.domains = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.domains.get().add(domainsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get domains
   * @return domains
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<String> getDomains() {
        return domains.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DOMAINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getDomains_JsonNullable() {
    return domains;
  }
  
  @JsonProperty(JSON_PROPERTY_DOMAINS)
  public void setDomains_JsonNullable(JsonNullable<List<String>> domains) {
    this.domains = domains;
  }

  public void setDomains(@javax.annotation.Nullable List<String> domains) {
    this.domains = JsonNullable.<List<String>>of(domains);
  }


  public MetricsFiltersEcho countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = JsonNullable.<String>of(countryCode);
    return this;
  }

  /**
   * Comma-separated country codes
   * @return countryCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCountryCode() {
        return countryCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COUNTRY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCountryCode_JsonNullable() {
    return countryCode;
  }
  
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  public void setCountryCode_JsonNullable(JsonNullable<String> countryCode) {
    this.countryCode = countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = JsonNullable.<String>of(countryCode);
  }


  public MetricsFiltersEcho languageCode(@javax.annotation.Nullable String languageCode) {
    this.languageCode = JsonNullable.<String>of(languageCode);
    return this;
  }

  /**
   * Comma-separated language codes
   * @return languageCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLanguageCode() {
        return languageCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LANGUAGE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLanguageCode_JsonNullable() {
    return languageCode;
  }
  
  @JsonProperty(JSON_PROPERTY_LANGUAGE_CODE)
  public void setLanguageCode_JsonNullable(JsonNullable<String> languageCode) {
    this.languageCode = languageCode;
  }

  public void setLanguageCode(@javax.annotation.Nullable String languageCode) {
    this.languageCode = JsonNullable.<String>of(languageCode);
  }


  public MetricsFiltersEcho prompt(@javax.annotation.Nullable Integer prompt) {
    this.prompt = JsonNullable.<Integer>of(prompt);
    return this;
  }

  /**
   * The prompt id filter
   * @return prompt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getPrompt() {
        return prompt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PROMPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getPrompt_JsonNullable() {
    return prompt;
  }
  
  @JsonProperty(JSON_PROPERTY_PROMPT)
  public void setPrompt_JsonNullable(JsonNullable<Integer> prompt) {
    this.prompt = prompt;
  }

  public void setPrompt(@javax.annotation.Nullable Integer prompt) {
    this.prompt = JsonNullable.<Integer>of(prompt);
  }


  public MetricsFiltersEcho promptType(@javax.annotation.Nullable String promptType) {
    this.promptType = JsonNullable.<String>of(promptType);
    return this;
  }

  /**
   * Comma-separated prompt types
   * @return promptType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPromptType() {
        return promptType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PROMPT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPromptType_JsonNullable() {
    return promptType;
  }
  
  @JsonProperty(JSON_PROPERTY_PROMPT_TYPE)
  public void setPromptType_JsonNullable(JsonNullable<String> promptType) {
    this.promptType = promptType;
  }

  public void setPromptType(@javax.annotation.Nullable String promptType) {
    this.promptType = JsonNullable.<String>of(promptType);
  }


  public MetricsFiltersEcho brandKind(@javax.annotation.Nullable String brandKind) {
    this.brandKind = JsonNullable.<String>of(brandKind);
    return this;
  }

  /**
   * Get brandKind
   * @return brandKind
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBrandKind() {
        return brandKind.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BRAND_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBrandKind_JsonNullable() {
    return brandKind;
  }
  
  @JsonProperty(JSON_PROPERTY_BRAND_KIND)
  public void setBrandKind_JsonNullable(JsonNullable<String> brandKind) {
    this.brandKind = brandKind;
  }

  public void setBrandKind(@javax.annotation.Nullable String brandKind) {
    this.brandKind = JsonNullable.<String>of(brandKind);
  }


  public MetricsFiltersEcho competitors(@javax.annotation.Nullable List<Integer> competitors) {
    this.competitors = competitors;
    return this;
  }

  public MetricsFiltersEcho addCompetitorsItem(Integer competitorsItem) {
    if (this.competitors == null) {
      this.competitors = new ArrayList<>();
    }
    this.competitors.add(competitorsItem);
    return this;
  }

  /**
   * Competitor ids from the competitors parameter; empty when it was not given
   * @return competitors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPETITORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Integer> getCompetitors() {
    return competitors;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPETITORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompetitors(@javax.annotation.Nullable List<Integer> competitors) {
    this.competitors = competitors;
  }


  public MetricsFiltersEcho includeProject(@javax.annotation.Nullable Boolean includeProject) {
    this.includeProject = includeProject;
    return this;
  }

  /**
   * Get includeProject
   * @return includeProject
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncludeProject() {
    return includeProject;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeProject(@javax.annotation.Nullable Boolean includeProject) {
    this.includeProject = includeProject;
  }


  public MetricsFiltersEcho query(@javax.annotation.Nullable String query) {
    this.query = query;
    return this;
  }

  /**
   * Only present when a query filter was given
   * @return query
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@javax.annotation.Nullable String query) {
    this.query = query;
  }


  /**
   * Return true if this MetricsFiltersEcho object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsFiltersEcho metricsFiltersEcho = (MetricsFiltersEcho) o;
    return Objects.equals(this.metrics, metricsFiltersEcho.metrics) &&
        Objects.equals(this.granularity, metricsFiltersEcho.granularity) &&
        equalsNullable(this.model, metricsFiltersEcho.model) &&
        equalsNullable(this.collectionId, metricsFiltersEcho.collectionId) &&
        equalsNullable(this.collectionIds, metricsFiltersEcho.collectionIds) &&
        equalsNullable(this.domains, metricsFiltersEcho.domains) &&
        equalsNullable(this.countryCode, metricsFiltersEcho.countryCode) &&
        equalsNullable(this.languageCode, metricsFiltersEcho.languageCode) &&
        equalsNullable(this.prompt, metricsFiltersEcho.prompt) &&
        equalsNullable(this.promptType, metricsFiltersEcho.promptType) &&
        equalsNullable(this.brandKind, metricsFiltersEcho.brandKind) &&
        Objects.equals(this.competitors, metricsFiltersEcho.competitors) &&
        Objects.equals(this.includeProject, metricsFiltersEcho.includeProject) &&
        Objects.equals(this.query, metricsFiltersEcho.query);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(metrics, granularity, hashCodeNullable(model), hashCodeNullable(collectionId), hashCodeNullable(collectionIds), hashCodeNullable(domains), hashCodeNullable(countryCode), hashCodeNullable(languageCode), hashCodeNullable(prompt), hashCodeNullable(promptType), hashCodeNullable(brandKind), competitors, includeProject, query);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetricsFiltersEcho {\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    granularity: ").append(toIndentedString(granularity)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    collectionIds: ").append(toIndentedString(collectionIds)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    promptType: ").append(toIndentedString(promptType)).append("\n");
    sb.append("    brandKind: ").append(toIndentedString(brandKind)).append("\n");
    sb.append("    competitors: ").append(toIndentedString(competitors)).append("\n");
    sb.append("    includeProject: ").append(toIndentedString(includeProject)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `metrics` to the URL query string
    if (getMetrics() != null) {
      for (int i = 0; i < getMetrics().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smetrics%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getMetrics().get(i)))));
      }
    }

    // add `granularity` to the URL query string
    if (getGranularity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgranularity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGranularity()))));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
    }

    // add `collection_id` to the URL query string
    if (getCollectionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scollection_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCollectionId()))));
    }

    // add `collection_ids` to the URL query string
    if (getCollectionIds() != null) {
      for (int i = 0; i < getCollectionIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scollection_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCollectionIds().get(i)))));
      }
    }

    // add `domains` to the URL query string
    if (getDomains() != null) {
      for (int i = 0; i < getDomains().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdomains%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDomains().get(i)))));
      }
    }

    // add `country_code` to the URL query string
    if (getCountryCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scountry_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountryCode()))));
    }

    // add `language_code` to the URL query string
    if (getLanguageCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slanguage_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLanguageCode()))));
    }

    // add `prompt` to the URL query string
    if (getPrompt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprompt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrompt()))));
    }

    // add `prompt_type` to the URL query string
    if (getPromptType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprompt_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPromptType()))));
    }

    // add `brand_kind` to the URL query string
    if (getBrandKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrand_kind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrandKind()))));
    }

    // add `competitors` to the URL query string
    if (getCompetitors() != null) {
      for (int i = 0; i < getCompetitors().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scompetitors%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCompetitors().get(i)))));
      }
    }

    // add `include_project` to the URL query string
    if (getIncludeProject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinclude_project%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIncludeProject()))));
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    return joiner.toString();
  }
}

