/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * AI models, countries and languages the project has data for
 */
@JsonPropertyOrder({
  ProjectDetailsAllOfDataCoverage.JSON_PROPERTY_MODELS,
  ProjectDetailsAllOfDataCoverage.JSON_PROPERTY_COUNTRIES,
  ProjectDetailsAllOfDataCoverage.JSON_PROPERTY_LANGUAGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ProjectDetailsAllOfDataCoverage {
  /**
   * Gets or Sets models
   */
  public enum ModelsEnum {
    CHATGPT(String.valueOf("chatgpt")),
    
    PERPLEXITY(String.valueOf("perplexity")),
    
    AI_MODE(String.valueOf("ai_mode")),
    
    AI_OVERVIEW(String.valueOf("ai_overview")),
    
    GEMINI(String.valueOf("gemini")),
    
    COPILOT(String.valueOf("copilot")),
    
    AMAZON_RUFUS(String.valueOf("amazon_rufus")),
    
    CLAUDE(String.valueOf("claude")),
    
    GROK(String.valueOf("grok")),
    
    DEEPSEEK(String.valueOf("deepseek")),
    
    NAVER_AI(String.valueOf("naver_ai")),
    
    BAIDU_AI(String.valueOf("baidu_ai")),
    
    META_AI(String.valueOf("meta_ai"));

    private String value;

    ModelsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModelsEnum fromValue(String value) {
      for (ModelsEnum b : ModelsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MODELS = "models";
  @javax.annotation.Nullable
  private List<ModelsEnum> models = new ArrayList<>();

  public static final String JSON_PROPERTY_COUNTRIES = "countries";
  @javax.annotation.Nullable
  private List<String> countries = new ArrayList<>();

  public static final String JSON_PROPERTY_LANGUAGES = "languages";
  @javax.annotation.Nullable
  private List<String> languages = new ArrayList<>();

  public ProjectDetailsAllOfDataCoverage() { 
  }

  public ProjectDetailsAllOfDataCoverage models(@javax.annotation.Nullable List<ModelsEnum> models) {
    this.models = models;
    return this;
  }

  public ProjectDetailsAllOfDataCoverage addModelsItem(ModelsEnum modelsItem) {
    if (this.models == null) {
      this.models = new ArrayList<>();
    }
    this.models.add(modelsItem);
    return this;
  }

  /**
   * Get models
   * @return models
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ModelsEnum> getModels() {
    return models;
  }


  @JsonProperty(value = JSON_PROPERTY_MODELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModels(@javax.annotation.Nullable List<ModelsEnum> models) {
    this.models = models;
  }


  public ProjectDetailsAllOfDataCoverage countries(@javax.annotation.Nullable List<String> countries) {
    this.countries = countries;
    return this;
  }

  public ProjectDetailsAllOfDataCoverage addCountriesItem(String countriesItem) {
    if (this.countries == null) {
      this.countries = new ArrayList<>();
    }
    this.countries.add(countriesItem);
    return this;
  }

  /**
   * Get countries
   * @return countries
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getCountries() {
    return countries;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountries(@javax.annotation.Nullable List<String> countries) {
    this.countries = countries;
  }


  public ProjectDetailsAllOfDataCoverage languages(@javax.annotation.Nullable List<String> languages) {
    this.languages = languages;
    return this;
  }

  public ProjectDetailsAllOfDataCoverage addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<>();
    }
    this.languages.add(languagesItem);
    return this;
  }

  /**
   * Get languages
   * @return languages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LANGUAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getLanguages() {
    return languages;
  }


  @JsonProperty(value = JSON_PROPERTY_LANGUAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguages(@javax.annotation.Nullable List<String> languages) {
    this.languages = languages;
  }


  /**
   * Return true if this ProjectDetails_allOf_data_coverage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDetailsAllOfDataCoverage projectDetailsAllOfDataCoverage = (ProjectDetailsAllOfDataCoverage) o;
    return Objects.equals(this.models, projectDetailsAllOfDataCoverage.models) &&
        Objects.equals(this.countries, projectDetailsAllOfDataCoverage.countries) &&
        Objects.equals(this.languages, projectDetailsAllOfDataCoverage.languages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(models, countries, languages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDetailsAllOfDataCoverage {\n");
    sb.append("    models: ").append(toIndentedString(models)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `models` to the URL query string
    if (getModels() != null) {
      for (int i = 0; i < getModels().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smodels%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getModels().get(i)))));
      }
    }

    // add `countries` to the URL query string
    if (getCountries() != null) {
      for (int i = 0; i < getCountries().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scountries%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCountries().get(i)))));
      }
    }

    // add `languages` to the URL query string
    if (getLanguages() != null) {
      for (int i = 0; i < getLanguages().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%slanguages%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getLanguages().get(i)))));
      }
    }

    return joiner.toString();
  }
}

