/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.ProjectCreateRequestCompetitorsInner;
import ai.llmpulse.sdk.model.ProjectCreateRequestOwnedMedia;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * ProjectCreateRequest
 */
@JsonPropertyOrder({
  ProjectCreateRequest.JSON_PROPERTY_WEBSITE_URL,
  ProjectCreateRequest.JSON_PROPERTY_NAME,
  ProjectCreateRequest.JSON_PROPERTY_MAIN_COUNTRY,
  ProjectCreateRequest.JSON_PROPERTY_MAIN_LANGUAGE,
  ProjectCreateRequest.JSON_PROPERTY_BRAND_NAME,
  ProjectCreateRequest.JSON_PROPERTY_DESCRIPTION,
  ProjectCreateRequest.JSON_PROPERTY_INDUSTRY,
  ProjectCreateRequest.JSON_PROPERTY_BUSINESS_MODEL,
  ProjectCreateRequest.JSON_PROPERTY_BUSINESS_MODEL_OTHER,
  ProjectCreateRequest.JSON_PROPERTY_TARGET_AUDIENCE,
  ProjectCreateRequest.JSON_PROPERTY_BRAND_VOICE,
  ProjectCreateRequest.JSON_PROPERTY_GOALS,
  ProjectCreateRequest.JSON_PROPERTY_PRIMARY_PRODUCTS,
  ProjectCreateRequest.JSON_PROPERTY_MATCHING_NAMES,
  ProjectCreateRequest.JSON_PROPERTY_PROMPTS,
  ProjectCreateRequest.JSON_PROPERTY_COMPETITORS,
  ProjectCreateRequest.JSON_PROPERTY_OWNED_MEDIA,
  ProjectCreateRequest.JSON_PROPERTY_USE_SUBDOMAIN,
  ProjectCreateRequest.JSON_PROPERTY_WEEKLY_EMAIL_SUBSCRIBED,
  ProjectCreateRequest.JSON_PROPERTY_EXTERNAL_IDENTIFIER,
  ProjectCreateRequest.JSON_PROPERTY_EXECUTE_PROMPTS_IMMEDIATELY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ProjectCreateRequest {
  public static final String JSON_PROPERTY_WEBSITE_URL = "website_url";
  @javax.annotation.Nonnull
  private URI websiteUrl;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_MAIN_COUNTRY = "main_country";
  @javax.annotation.Nonnull
  private String mainCountry;

  public static final String JSON_PROPERTY_MAIN_LANGUAGE = "main_language";
  @javax.annotation.Nonnull
  private String mainLanguage;

  public static final String JSON_PROPERTY_BRAND_NAME = "brand_name";
  @javax.annotation.Nullable
  private String brandName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_INDUSTRY = "industry";
  @javax.annotation.Nullable
  private List<String> industry = new ArrayList<>();

  public static final String JSON_PROPERTY_BUSINESS_MODEL = "business_model";
  @javax.annotation.Nullable
  private String businessModel;

  public static final String JSON_PROPERTY_BUSINESS_MODEL_OTHER = "business_model_other";
  @javax.annotation.Nullable
  private String businessModelOther;

  public static final String JSON_PROPERTY_TARGET_AUDIENCE = "target_audience";
  @javax.annotation.Nullable
  private String targetAudience;

  public static final String JSON_PROPERTY_BRAND_VOICE = "brand_voice";
  @javax.annotation.Nullable
  private String brandVoice;

  public static final String JSON_PROPERTY_GOALS = "goals";
  @javax.annotation.Nullable
  private String goals;

  public static final String JSON_PROPERTY_PRIMARY_PRODUCTS = "primary_products";
  @javax.annotation.Nullable
  private List<String> primaryProducts = new ArrayList<>();

  public static final String JSON_PROPERTY_MATCHING_NAMES = "matching_names";
  @javax.annotation.Nullable
  private List<String> matchingNames = new ArrayList<>();

  public static final String JSON_PROPERTY_PROMPTS = "prompts";
  @javax.annotation.Nullable
  private List<String> prompts = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPETITORS = "competitors";
  @javax.annotation.Nullable
  private List<ProjectCreateRequestCompetitorsInner> competitors = new ArrayList<>();

  public static final String JSON_PROPERTY_OWNED_MEDIA = "owned_media";
  @javax.annotation.Nullable
  private ProjectCreateRequestOwnedMedia ownedMedia;

  public static final String JSON_PROPERTY_USE_SUBDOMAIN = "use_subdomain";
  @javax.annotation.Nullable
  private Boolean useSubdomain = false;

  public static final String JSON_PROPERTY_WEEKLY_EMAIL_SUBSCRIBED = "weekly_email_subscribed";
  @javax.annotation.Nullable
  private Boolean weeklyEmailSubscribed = false;

  public static final String JSON_PROPERTY_EXTERNAL_IDENTIFIER = "external_identifier";
  @javax.annotation.Nullable
  private String externalIdentifier;

  public static final String JSON_PROPERTY_EXECUTE_PROMPTS_IMMEDIATELY = "execute_prompts_immediately";
  @javax.annotation.Nullable
  private Boolean executePromptsImmediately = true;

  public ProjectCreateRequest() { 
  }

  public ProjectCreateRequest websiteUrl(@javax.annotation.Nonnull URI websiteUrl) {
    this.websiteUrl = websiteUrl;
    return this;
  }

  /**
   * Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
   * @return websiteUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WEBSITE_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getWebsiteUrl() {
    return websiteUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBSITE_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebsiteUrl(@javax.annotation.Nonnull URI websiteUrl) {
    this.websiteUrl = websiteUrl;
  }


  public ProjectCreateRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ProjectCreateRequest mainCountry(@javax.annotation.Nonnull String mainCountry) {
    this.mainCountry = mainCountry;
    return this;
  }

  /**
   * Get mainCountry
   * @return mainCountry
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAIN_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMainCountry() {
    return mainCountry;
  }


  @JsonProperty(value = JSON_PROPERTY_MAIN_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMainCountry(@javax.annotation.Nonnull String mainCountry) {
    this.mainCountry = mainCountry;
  }


  public ProjectCreateRequest mainLanguage(@javax.annotation.Nonnull String mainLanguage) {
    this.mainLanguage = mainLanguage;
    return this;
  }

  /**
   * Get mainLanguage
   * @return mainLanguage
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAIN_LANGUAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMainLanguage() {
    return mainLanguage;
  }


  @JsonProperty(value = JSON_PROPERTY_MAIN_LANGUAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMainLanguage(@javax.annotation.Nonnull String mainLanguage) {
    this.mainLanguage = mainLanguage;
  }


  public ProjectCreateRequest brandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Get brandName
   * @return brandName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRAND_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBrandName() {
    return brandName;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
  }


  public ProjectCreateRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public ProjectCreateRequest industry(@javax.annotation.Nullable List<String> industry) {
    this.industry = industry;
    return this;
  }

  public ProjectCreateRequest addIndustryItem(String industryItem) {
    if (this.industry == null) {
      this.industry = new ArrayList<>();
    }
    this.industry.add(industryItem);
    return this;
  }

  /**
   * Get industry
   * @return industry
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getIndustry() {
    return industry;
  }


  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustry(@javax.annotation.Nullable List<String> industry) {
    this.industry = industry;
  }


  public ProjectCreateRequest businessModel(@javax.annotation.Nullable String businessModel) {
    this.businessModel = businessModel;
    return this;
  }

  /**
   * Business model key (e.g. B2B_SAAS, MARKETPLACE); unknown keys are rejected
   * @return businessModel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBusinessModel() {
    return businessModel;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessModel(@javax.annotation.Nullable String businessModel) {
    this.businessModel = businessModel;
  }


  public ProjectCreateRequest businessModelOther(@javax.annotation.Nullable String businessModelOther) {
    this.businessModelOther = businessModelOther;
    return this;
  }

  /**
   * Free-text business model, only accepted when business_model is OTHER; rejected against any other key
   * @return businessModelOther
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_MODEL_OTHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBusinessModelOther() {
    return businessModelOther;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_MODEL_OTHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessModelOther(@javax.annotation.Nullable String businessModelOther) {
    this.businessModelOther = businessModelOther;
  }


  public ProjectCreateRequest targetAudience(@javax.annotation.Nullable String targetAudience) {
    this.targetAudience = targetAudience;
    return this;
  }

  /**
   * Who the brand sells to. Context for Recommendations and GEO Writer (Brand Book)
   * @return targetAudience
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTargetAudience() {
    return targetAudience;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetAudience(@javax.annotation.Nullable String targetAudience) {
    this.targetAudience = targetAudience;
  }


  public ProjectCreateRequest brandVoice(@javax.annotation.Nullable String brandVoice) {
    this.brandVoice = brandVoice;
    return this;
  }

  /**
   * Tone of voice guidance for generated content (Brand Book)
   * @return brandVoice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRAND_VOICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBrandVoice() {
    return brandVoice;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND_VOICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandVoice(@javax.annotation.Nullable String brandVoice) {
    this.brandVoice = brandVoice;
  }


  public ProjectCreateRequest goals(@javax.annotation.Nullable String goals) {
    this.goals = goals;
    return this;
  }

  /**
   * What the brand wants to achieve. Context for GEO Writer and prompt suggestions
   * @return goals
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GOALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGoals() {
    return goals;
  }


  @JsonProperty(value = JSON_PROPERTY_GOALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoals(@javax.annotation.Nullable String goals) {
    this.goals = goals;
  }


  public ProjectCreateRequest primaryProducts(@javax.annotation.Nullable List<String> primaryProducts) {
    this.primaryProducts = primaryProducts;
    return this;
  }

  public ProjectCreateRequest addPrimaryProductsItem(String primaryProductsItem) {
    if (this.primaryProducts == null) {
      this.primaryProducts = new ArrayList<>();
    }
    this.primaryProducts.add(primaryProductsItem);
    return this;
  }

  /**
   * Main products or services
   * @return primaryProducts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIMARY_PRODUCTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPrimaryProducts() {
    return primaryProducts;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIMARY_PRODUCTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrimaryProducts(@javax.annotation.Nullable List<String> primaryProducts) {
    this.primaryProducts = primaryProducts;
  }


  public ProjectCreateRequest matchingNames(@javax.annotation.Nullable List<String> matchingNames) {
    this.matchingNames = matchingNames;
    return this;
  }

  public ProjectCreateRequest addMatchingNamesItem(String matchingNamesItem) {
    if (this.matchingNames == null) {
      this.matchingNames = new ArrayList<>();
    }
    this.matchingNames.add(matchingNamesItem);
    return this;
  }

  /**
   * Get matchingNames
   * @return matchingNames
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MATCHING_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getMatchingNames() {
    return matchingNames;
  }


  @JsonProperty(value = JSON_PROPERTY_MATCHING_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchingNames(@javax.annotation.Nullable List<String> matchingNames) {
    this.matchingNames = matchingNames;
  }


  public ProjectCreateRequest prompts(@javax.annotation.Nullable List<String> prompts) {
    this.prompts = prompts;
    return this;
  }

  public ProjectCreateRequest addPromptsItem(String promptsItem) {
    if (this.prompts == null) {
      this.prompts = new ArrayList<>();
    }
    this.prompts.add(promptsItem);
    return this;
  }

  /**
   * Get prompts
   * @return prompts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROMPTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPrompts() {
    return prompts;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrompts(@javax.annotation.Nullable List<String> prompts) {
    this.prompts = prompts;
  }


  public ProjectCreateRequest competitors(@javax.annotation.Nullable List<ProjectCreateRequestCompetitorsInner> competitors) {
    this.competitors = competitors;
    return this;
  }

  public ProjectCreateRequest addCompetitorsItem(ProjectCreateRequestCompetitorsInner competitorsItem) {
    if (this.competitors == null) {
      this.competitors = new ArrayList<>();
    }
    this.competitors.add(competitorsItem);
    return this;
  }

  /**
   * Get competitors
   * @return competitors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPETITORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ProjectCreateRequestCompetitorsInner> getCompetitors() {
    return competitors;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPETITORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompetitors(@javax.annotation.Nullable List<ProjectCreateRequestCompetitorsInner> competitors) {
    this.competitors = competitors;
  }


  public ProjectCreateRequest ownedMedia(@javax.annotation.Nullable ProjectCreateRequestOwnedMedia ownedMedia) {
    this.ownedMedia = ownedMedia;
    return this;
  }

  /**
   * Get ownedMedia
   * @return ownedMedia
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNED_MEDIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProjectCreateRequestOwnedMedia getOwnedMedia() {
    return ownedMedia;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNED_MEDIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnedMedia(@javax.annotation.Nullable ProjectCreateRequestOwnedMedia ownedMedia) {
    this.ownedMedia = ownedMedia;
  }


  public ProjectCreateRequest useSubdomain(@javax.annotation.Nullable Boolean useSubdomain) {
    this.useSubdomain = useSubdomain;
    return this;
  }

  /**
   * Get useSubdomain
   * @return useSubdomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USE_SUBDOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getUseSubdomain() {
    return useSubdomain;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_SUBDOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseSubdomain(@javax.annotation.Nullable Boolean useSubdomain) {
    this.useSubdomain = useSubdomain;
  }


  public ProjectCreateRequest weeklyEmailSubscribed(@javax.annotation.Nullable Boolean weeklyEmailSubscribed) {
    this.weeklyEmailSubscribed = weeklyEmailSubscribed;
    return this;
  }

  /**
   * Get weeklyEmailSubscribed
   * @return weeklyEmailSubscribed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEEKLY_EMAIL_SUBSCRIBED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getWeeklyEmailSubscribed() {
    return weeklyEmailSubscribed;
  }


  @JsonProperty(value = JSON_PROPERTY_WEEKLY_EMAIL_SUBSCRIBED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeeklyEmailSubscribed(@javax.annotation.Nullable Boolean weeklyEmailSubscribed) {
    this.weeklyEmailSubscribed = weeklyEmailSubscribed;
  }


  public ProjectCreateRequest externalIdentifier(@javax.annotation.Nullable String externalIdentifier) {
    this.externalIdentifier = externalIdentifier;
    return this;
  }

  /**
   * Embed-enabled (Enterprise) accounts only; other accounts receive ERR_PLAN_REQUIRED. Idempotency key and embed-session join key, unique per account
   * @return externalIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExternalIdentifier() {
    return externalIdentifier;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalIdentifier(@javax.annotation.Nullable String externalIdentifier) {
    this.externalIdentifier = externalIdentifier;
  }


  public ProjectCreateRequest executePromptsImmediately(@javax.annotation.Nullable Boolean executePromptsImmediately) {
    this.executePromptsImmediately = executePromptsImmediately;
    return this;
  }

  /**
   * Get executePromptsImmediately
   * @return executePromptsImmediately
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXECUTE_PROMPTS_IMMEDIATELY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getExecutePromptsImmediately() {
    return executePromptsImmediately;
  }


  @JsonProperty(value = JSON_PROPERTY_EXECUTE_PROMPTS_IMMEDIATELY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutePromptsImmediately(@javax.annotation.Nullable Boolean executePromptsImmediately) {
    this.executePromptsImmediately = executePromptsImmediately;
  }


  /**
   * Return true if this ProjectCreateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectCreateRequest projectCreateRequest = (ProjectCreateRequest) o;
    return Objects.equals(this.websiteUrl, projectCreateRequest.websiteUrl) &&
        Objects.equals(this.name, projectCreateRequest.name) &&
        Objects.equals(this.mainCountry, projectCreateRequest.mainCountry) &&
        Objects.equals(this.mainLanguage, projectCreateRequest.mainLanguage) &&
        Objects.equals(this.brandName, projectCreateRequest.brandName) &&
        Objects.equals(this.description, projectCreateRequest.description) &&
        Objects.equals(this.industry, projectCreateRequest.industry) &&
        Objects.equals(this.businessModel, projectCreateRequest.businessModel) &&
        Objects.equals(this.businessModelOther, projectCreateRequest.businessModelOther) &&
        Objects.equals(this.targetAudience, projectCreateRequest.targetAudience) &&
        Objects.equals(this.brandVoice, projectCreateRequest.brandVoice) &&
        Objects.equals(this.goals, projectCreateRequest.goals) &&
        Objects.equals(this.primaryProducts, projectCreateRequest.primaryProducts) &&
        Objects.equals(this.matchingNames, projectCreateRequest.matchingNames) &&
        Objects.equals(this.prompts, projectCreateRequest.prompts) &&
        Objects.equals(this.competitors, projectCreateRequest.competitors) &&
        Objects.equals(this.ownedMedia, projectCreateRequest.ownedMedia) &&
        Objects.equals(this.useSubdomain, projectCreateRequest.useSubdomain) &&
        Objects.equals(this.weeklyEmailSubscribed, projectCreateRequest.weeklyEmailSubscribed) &&
        Objects.equals(this.externalIdentifier, projectCreateRequest.externalIdentifier) &&
        Objects.equals(this.executePromptsImmediately, projectCreateRequest.executePromptsImmediately);
  }

  @Override
  public int hashCode() {
    return Objects.hash(websiteUrl, name, mainCountry, mainLanguage, brandName, description, industry, businessModel, businessModelOther, targetAudience, brandVoice, goals, primaryProducts, matchingNames, prompts, competitors, ownedMedia, useSubdomain, weeklyEmailSubscribed, externalIdentifier, executePromptsImmediately);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectCreateRequest {\n");
    sb.append("    websiteUrl: ").append(toIndentedString(websiteUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mainCountry: ").append(toIndentedString(mainCountry)).append("\n");
    sb.append("    mainLanguage: ").append(toIndentedString(mainLanguage)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    businessModel: ").append(toIndentedString(businessModel)).append("\n");
    sb.append("    businessModelOther: ").append(toIndentedString(businessModelOther)).append("\n");
    sb.append("    targetAudience: ").append(toIndentedString(targetAudience)).append("\n");
    sb.append("    brandVoice: ").append(toIndentedString(brandVoice)).append("\n");
    sb.append("    goals: ").append(toIndentedString(goals)).append("\n");
    sb.append("    primaryProducts: ").append(toIndentedString(primaryProducts)).append("\n");
    sb.append("    matchingNames: ").append(toIndentedString(matchingNames)).append("\n");
    sb.append("    prompts: ").append(toIndentedString(prompts)).append("\n");
    sb.append("    competitors: ").append(toIndentedString(competitors)).append("\n");
    sb.append("    ownedMedia: ").append(toIndentedString(ownedMedia)).append("\n");
    sb.append("    useSubdomain: ").append(toIndentedString(useSubdomain)).append("\n");
    sb.append("    weeklyEmailSubscribed: ").append(toIndentedString(weeklyEmailSubscribed)).append("\n");
    sb.append("    externalIdentifier: ").append(toIndentedString(externalIdentifier)).append("\n");
    sb.append("    executePromptsImmediately: ").append(toIndentedString(executePromptsImmediately)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `website_url` to the URL query string
    if (getWebsiteUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebsite_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebsiteUrl()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `main_country` to the URL query string
    if (getMainCountry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smain_country%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMainCountry()))));
    }

    // add `main_language` to the URL query string
    if (getMainLanguage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smain_language%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMainLanguage()))));
    }

    // add `brand_name` to the URL query string
    if (getBrandName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrand_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrandName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `industry` to the URL query string
    if (getIndustry() != null) {
      for (int i = 0; i < getIndustry().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sindustry%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getIndustry().get(i)))));
      }
    }

    // add `business_model` to the URL query string
    if (getBusinessModel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbusiness_model%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBusinessModel()))));
    }

    // add `business_model_other` to the URL query string
    if (getBusinessModelOther() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbusiness_model_other%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBusinessModelOther()))));
    }

    // add `target_audience` to the URL query string
    if (getTargetAudience() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%starget_audience%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetAudience()))));
    }

    // add `brand_voice` to the URL query string
    if (getBrandVoice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrand_voice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrandVoice()))));
    }

    // add `goals` to the URL query string
    if (getGoals() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgoals%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGoals()))));
    }

    // add `primary_products` to the URL query string
    if (getPrimaryProducts() != null) {
      for (int i = 0; i < getPrimaryProducts().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprimary_products%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPrimaryProducts().get(i)))));
      }
    }

    // add `matching_names` to the URL query string
    if (getMatchingNames() != null) {
      for (int i = 0; i < getMatchingNames().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smatching_names%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getMatchingNames().get(i)))));
      }
    }

    // add `prompts` to the URL query string
    if (getPrompts() != null) {
      for (int i = 0; i < getPrompts().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprompts%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPrompts().get(i)))));
      }
    }

    // add `competitors` to the URL query string
    if (getCompetitors() != null) {
      for (int i = 0; i < getCompetitors().size(); i++) {
        if (getCompetitors().get(i) != null) {
          joiner.add(getCompetitors().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scompetitors%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `owned_media` to the URL query string
    if (getOwnedMedia() != null) {
      joiner.add(getOwnedMedia().toUrlQueryString(prefix + "owned_media" + suffix));
    }

    // add `use_subdomain` to the URL query string
    if (getUseSubdomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suse_subdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUseSubdomain()))));
    }

    // add `weekly_email_subscribed` to the URL query string
    if (getWeeklyEmailSubscribed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sweekly_email_subscribed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWeeklyEmailSubscribed()))));
    }

    // add `external_identifier` to the URL query string
    if (getExternalIdentifier() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexternal_identifier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalIdentifier()))));
    }

    // add `execute_prompts_immediately` to the URL query string
    if (getExecutePromptsImmediately() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexecute_prompts_immediately%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExecutePromptsImmediately()))));
    }

    return joiner.toString();
  }
}

