/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.51.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.PromptSummaryRow;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * PromptSummaryResponse
 */
@JsonPropertyOrder({
  PromptSummaryResponse.JSON_PROPERTY_PROJECT_ID,
  PromptSummaryResponse.JSON_PROPERTY_FROM,
  PromptSummaryResponse.JSON_PROPERTY_TO,
  PromptSummaryResponse.JSON_PROPERTY_FILTERS,
  PromptSummaryResponse.JSON_PROPERTY_BREAKDOWN,
  PromptSummaryResponse.JSON_PROPERTY_SORT,
  PromptSummaryResponse.JSON_PROPERTY_SORT_DIR,
  PromptSummaryResponse.JSON_PROPERTY_PAGE,
  PromptSummaryResponse.JSON_PROPERTY_PER_PAGE,
  PromptSummaryResponse.JSON_PROPERTY_TOTAL,
  PromptSummaryResponse.JSON_PROPERTY_DATA,
  PromptSummaryResponse.JSON_PROPERTY_REQUEST_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PromptSummaryResponse {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nullable
  private OffsetDateTime from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nullable
  private OffsetDateTime to;

  public static final String JSON_PROPERTY_FILTERS = "filters";
  @javax.annotation.Nullable
  private Object filters;

  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  private JsonNullable<String> breakdown = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SORT = "sort";
  @javax.annotation.Nullable
  private String sort;

  public static final String JSON_PROPERTY_SORT_DIR = "sort_dir";
  @javax.annotation.Nullable
  private String sortDir;

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable
  private Integer page;

  public static final String JSON_PROPERTY_PER_PAGE = "per_page";
  @javax.annotation.Nullable
  private Integer perPage;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nullable
  private Integer total;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<PromptSummaryRow> data = new ArrayList<>();

  public static final String JSON_PROPERTY_REQUEST_ID = "request_id";
  @javax.annotation.Nullable
  private String requestId;

  public PromptSummaryResponse() { 
  }

  public PromptSummaryResponse projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public PromptSummaryResponse from(@javax.annotation.Nullable OffsetDateTime from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrom(@javax.annotation.Nullable OffsetDateTime from) {
    this.from = from;
  }


  public PromptSummaryResponse to(@javax.annotation.Nullable OffsetDateTime to) {
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTo(@javax.annotation.Nullable OffsetDateTime to) {
    this.to = to;
  }


  public PromptSummaryResponse filters(@javax.annotation.Nullable Object filters) {
    this.filters = filters;
    return this;
  }

  /**
   * Get filters
   * @return filters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getFilters() {
    return filters;
  }


  @JsonProperty(value = JSON_PROPERTY_FILTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilters(@javax.annotation.Nullable Object filters) {
    this.filters = filters;
  }


  public PromptSummaryResponse breakdown(@javax.annotation.Nullable String breakdown) {
    this.breakdown = JsonNullable.<String>of(breakdown);
    return this;
  }

  /**
   * Get breakdown
   * @return breakdown
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBreakdown() {
        return breakdown.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBreakdown_JsonNullable() {
    return breakdown;
  }
  
  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  public void setBreakdown_JsonNullable(JsonNullable<String> breakdown) {
    this.breakdown = breakdown;
  }

  public void setBreakdown(@javax.annotation.Nullable String breakdown) {
    this.breakdown = JsonNullable.<String>of(breakdown);
  }


  public PromptSummaryResponse sort(@javax.annotation.Nullable String sort) {
    this.sort = sort;
    return this;
  }

  /**
   * Get sort
   * @return sort
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSort() {
    return sort;
  }


  @JsonProperty(value = JSON_PROPERTY_SORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSort(@javax.annotation.Nullable String sort) {
    this.sort = sort;
  }


  public PromptSummaryResponse sortDir(@javax.annotation.Nullable String sortDir) {
    this.sortDir = sortDir;
    return this;
  }

  /**
   * Get sortDir
   * @return sortDir
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SORT_DIR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSortDir() {
    return sortDir;
  }


  @JsonProperty(value = JSON_PROPERTY_SORT_DIR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortDir(@javax.annotation.Nullable String sortDir) {
    this.sortDir = sortDir;
  }


  public PromptSummaryResponse page(@javax.annotation.Nullable Integer page) {
    this.page = page;
    return this;
  }

  /**
   * Get page
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPage() {
    return page;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable Integer page) {
    this.page = page;
  }


  public PromptSummaryResponse perPage(@javax.annotation.Nullable Integer perPage) {
    this.perPage = perPage;
    return this;
  }

  /**
   * Get perPage
   * @return perPage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PER_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPerPage() {
    return perPage;
  }


  @JsonProperty(value = JSON_PROPERTY_PER_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerPage(@javax.annotation.Nullable Integer perPage) {
    this.perPage = perPage;
  }


  public PromptSummaryResponse total(@javax.annotation.Nullable Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(@javax.annotation.Nullable Integer total) {
    this.total = total;
  }


  public PromptSummaryResponse data(@javax.annotation.Nullable List<PromptSummaryRow> data) {
    this.data = data;
    return this;
  }

  public PromptSummaryResponse addDataItem(PromptSummaryRow dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PromptSummaryRow> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<PromptSummaryRow> data) {
    this.data = data;
  }


  public PromptSummaryResponse requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  /**
   * Return true if this PromptSummaryResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptSummaryResponse promptSummaryResponse = (PromptSummaryResponse) o;
    return Objects.equals(this.projectId, promptSummaryResponse.projectId) &&
        Objects.equals(this.from, promptSummaryResponse.from) &&
        Objects.equals(this.to, promptSummaryResponse.to) &&
        Objects.equals(this.filters, promptSummaryResponse.filters) &&
        equalsNullable(this.breakdown, promptSummaryResponse.breakdown) &&
        Objects.equals(this.sort, promptSummaryResponse.sort) &&
        Objects.equals(this.sortDir, promptSummaryResponse.sortDir) &&
        Objects.equals(this.page, promptSummaryResponse.page) &&
        Objects.equals(this.perPage, promptSummaryResponse.perPage) &&
        Objects.equals(this.total, promptSummaryResponse.total) &&
        Objects.equals(this.data, promptSummaryResponse.data) &&
        Objects.equals(this.requestId, promptSummaryResponse.requestId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, from, to, filters, hashCodeNullable(breakdown), sort, sortDir, page, perPage, total, data, requestId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptSummaryResponse {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    sortDir: ").append(toIndentedString(sortDir)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTo()))));
    }

    // add `filters` to the URL query string
    if (getFilters() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilters%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilters()))));
    }

    // add `breakdown` to the URL query string
    if (getBreakdown() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbreakdown%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBreakdown()))));
    }

    // add `sort` to the URL query string
    if (getSort() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssort%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSort()))));
    }

    // add `sort_dir` to the URL query string
    if (getSortDir() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssort_dir%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSortDir()))));
    }

    // add `page` to the URL query string
    if (getPage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPage()))));
    }

    // add `per_page` to the URL query string
    if (getPerPage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sper_page%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPerPage()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (int i = 0; i < getData().size(); i++) {
        if (getData().get(i) != null) {
          joiner.add(getData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `request_id` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequest_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    return joiner.toString();
  }
}

