/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.PromptsCreateResponseDataInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * PromptsCreateResponse
 */
@JsonPropertyOrder({
  PromptsCreateResponse.JSON_PROPERTY_PROJECT_ID,
  PromptsCreateResponse.JSON_PROPERTY_CREATED,
  PromptsCreateResponse.JSON_PROPERTY_SKIPPED,
  PromptsCreateResponse.JSON_PROPERTY_TOTAL_AFTER,
  PromptsCreateResponse.JSON_PROPERTY_PROMPTS_AVAILABLE,
  PromptsCreateResponse.JSON_PROPERTY_DATA,
  PromptsCreateResponse.JSON_PROPERTY_REQUEST_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PromptsCreateResponse {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private Integer created;

  public static final String JSON_PROPERTY_SKIPPED = "skipped";
  @javax.annotation.Nullable
  private Integer skipped;

  public static final String JSON_PROPERTY_TOTAL_AFTER = "total_after";
  @javax.annotation.Nullable
  private Integer totalAfter;

  public static final String JSON_PROPERTY_PROMPTS_AVAILABLE = "prompts_available";
  @javax.annotation.Nullable
  private Integer promptsAvailable;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<PromptsCreateResponseDataInner> data = new ArrayList<>();

  public static final String JSON_PROPERTY_REQUEST_ID = "request_id";
  @javax.annotation.Nullable
  private String requestId;

  public PromptsCreateResponse() { 
  }

  public PromptsCreateResponse projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public PromptsCreateResponse created(@javax.annotation.Nullable Integer created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(@javax.annotation.Nullable Integer created) {
    this.created = created;
  }


  public PromptsCreateResponse skipped(@javax.annotation.Nullable Integer skipped) {
    this.skipped = skipped;
    return this;
  }

  /**
   * Get skipped
   * @return skipped
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SKIPPED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSkipped() {
    return skipped;
  }


  @JsonProperty(value = JSON_PROPERTY_SKIPPED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkipped(@javax.annotation.Nullable Integer skipped) {
    this.skipped = skipped;
  }


  public PromptsCreateResponse totalAfter(@javax.annotation.Nullable Integer totalAfter) {
    this.totalAfter = totalAfter;
    return this;
  }

  /**
   * Get totalAfter
   * @return totalAfter
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_AFTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalAfter() {
    return totalAfter;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_AFTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAfter(@javax.annotation.Nullable Integer totalAfter) {
    this.totalAfter = totalAfter;
  }


  public PromptsCreateResponse promptsAvailable(@javax.annotation.Nullable Integer promptsAvailable) {
    this.promptsAvailable = promptsAvailable;
    return this;
  }

  /**
   * Get promptsAvailable
   * @return promptsAvailable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROMPTS_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPromptsAvailable() {
    return promptsAvailable;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPTS_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromptsAvailable(@javax.annotation.Nullable Integer promptsAvailable) {
    this.promptsAvailable = promptsAvailable;
  }


  public PromptsCreateResponse data(@javax.annotation.Nullable List<PromptsCreateResponseDataInner> data) {
    this.data = data;
    return this;
  }

  public PromptsCreateResponse addDataItem(PromptsCreateResponseDataInner dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PromptsCreateResponseDataInner> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<PromptsCreateResponseDataInner> data) {
    this.data = data;
  }


  public PromptsCreateResponse requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  /**
   * Return true if this PromptsCreateResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptsCreateResponse promptsCreateResponse = (PromptsCreateResponse) o;
    return Objects.equals(this.projectId, promptsCreateResponse.projectId) &&
        Objects.equals(this.created, promptsCreateResponse.created) &&
        Objects.equals(this.skipped, promptsCreateResponse.skipped) &&
        Objects.equals(this.totalAfter, promptsCreateResponse.totalAfter) &&
        Objects.equals(this.promptsAvailable, promptsCreateResponse.promptsAvailable) &&
        Objects.equals(this.data, promptsCreateResponse.data) &&
        Objects.equals(this.requestId, promptsCreateResponse.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, created, skipped, totalAfter, promptsAvailable, data, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptsCreateResponse {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    totalAfter: ").append(toIndentedString(totalAfter)).append("\n");
    sb.append("    promptsAvailable: ").append(toIndentedString(promptsAvailable)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreated()))));
    }

    // add `skipped` to the URL query string
    if (getSkipped() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sskipped%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSkipped()))));
    }

    // add `total_after` to the URL query string
    if (getTotalAfter() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal_after%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalAfter()))));
    }

    // add `prompts_available` to the URL query string
    if (getPromptsAvailable() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprompts_available%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPromptsAvailable()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (int i = 0; i < getData().size(); i++) {
        if (getData().get(i) != null) {
          joiner.add(getData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `request_id` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequest_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    return joiner.toString();
  }
}

