/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * Empty until the generation completes
 */
@JsonPropertyOrder({
  RecommendationSummarySummary.JSON_PROPERTY_TOTAL_RECOMMENDATIONS,
  RecommendationSummarySummary.JSON_PROPERTY_HIGH_PRIORITY_COUNT,
  RecommendationSummarySummary.JSON_PROPERTY_CATEGORIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class RecommendationSummarySummary {
  public static final String JSON_PROPERTY_TOTAL_RECOMMENDATIONS = "total_recommendations";
  @javax.annotation.Nullable
  private Integer totalRecommendations;

  public static final String JSON_PROPERTY_HIGH_PRIORITY_COUNT = "high_priority_count";
  @javax.annotation.Nullable
  private Integer highPriorityCount;

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  @javax.annotation.Nullable
  private List<String> categories = new ArrayList<>();

  public RecommendationSummarySummary() { 
  }

  public RecommendationSummarySummary totalRecommendations(@javax.annotation.Nullable Integer totalRecommendations) {
    this.totalRecommendations = totalRecommendations;
    return this;
  }

  /**
   * Get totalRecommendations
   * @return totalRecommendations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_RECOMMENDATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalRecommendations() {
    return totalRecommendations;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_RECOMMENDATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRecommendations(@javax.annotation.Nullable Integer totalRecommendations) {
    this.totalRecommendations = totalRecommendations;
  }


  public RecommendationSummarySummary highPriorityCount(@javax.annotation.Nullable Integer highPriorityCount) {
    this.highPriorityCount = highPriorityCount;
    return this;
  }

  /**
   * Get highPriorityCount
   * @return highPriorityCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH_PRIORITY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getHighPriorityCount() {
    return highPriorityCount;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH_PRIORITY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighPriorityCount(@javax.annotation.Nullable Integer highPriorityCount) {
    this.highPriorityCount = highPriorityCount;
  }


  public RecommendationSummarySummary categories(@javax.annotation.Nullable List<String> categories) {
    this.categories = categories;
    return this;
  }

  public RecommendationSummarySummary addCategoriesItem(String categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

  /**
   * Get categories
   * @return categories
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getCategories() {
    return categories;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategories(@javax.annotation.Nullable List<String> categories) {
    this.categories = categories;
  }


  /**
   * Return true if this RecommendationSummary_summary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationSummarySummary recommendationSummarySummary = (RecommendationSummarySummary) o;
    return Objects.equals(this.totalRecommendations, recommendationSummarySummary.totalRecommendations) &&
        Objects.equals(this.highPriorityCount, recommendationSummarySummary.highPriorityCount) &&
        Objects.equals(this.categories, recommendationSummarySummary.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalRecommendations, highPriorityCount, categories);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationSummarySummary {\n");
    sb.append("    totalRecommendations: ").append(toIndentedString(totalRecommendations)).append("\n");
    sb.append("    highPriorityCount: ").append(toIndentedString(highPriorityCount)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `total_recommendations` to the URL query string
    if (getTotalRecommendations() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal_recommendations%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalRecommendations()))));
    }

    // add `high_priority_count` to the URL query string
    if (getHighPriorityCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shigh_priority_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHighPriorityCount()))));
    }

    // add `categories` to the URL query string
    if (getCategories() != null) {
      for (int i = 0; i < getCategories().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scategories%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCategories().get(i)))));
      }
    }

    return joiner.toString();
  }
}

