/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.SovResponseBreakdownInner;
import ai.llmpulse.sdk.model.SovResponseCurrentInner;
import ai.llmpulse.sdk.model.SovResponseOverTimeInner;
import ai.llmpulse.sdk.model.SovResponsePeriodsInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * SovResponse
 */
@JsonPropertyOrder({
  SovResponse.JSON_PROPERTY_PROJECT_ID,
  SovResponse.JSON_PROPERTY_PERIODS,
  SovResponse.JSON_PROPERTY_OVER_TIME,
  SovResponse.JSON_PROPERTY_CURRENT,
  SovResponse.JSON_PROPERTY_BREAKDOWN,
  SovResponse.JSON_PROPERTY_OTHERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SovResponse {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_PERIODS = "periods";
  @javax.annotation.Nullable
  private List<SovResponsePeriodsInner> periods = new ArrayList<>();

  public static final String JSON_PROPERTY_OVER_TIME = "over_time";
  @javax.annotation.Nullable
  private List<SovResponseOverTimeInner> overTime = new ArrayList<>();

  public static final String JSON_PROPERTY_CURRENT = "current";
  @javax.annotation.Nullable
  private List<SovResponseCurrentInner> current = new ArrayList<>();

  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  @javax.annotation.Nullable
  private List<SovResponseBreakdownInner> breakdown = new ArrayList<>();

  public static final String JSON_PROPERTY_OTHERS = "others";
  @javax.annotation.Nullable
  private List<Object> others = new ArrayList<>();

  public SovResponse() { 
  }

  public SovResponse projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public SovResponse periods(@javax.annotation.Nullable List<SovResponsePeriodsInner> periods) {
    this.periods = periods;
    return this;
  }

  public SovResponse addPeriodsItem(SovResponsePeriodsInner periodsItem) {
    if (this.periods == null) {
      this.periods = new ArrayList<>();
    }
    this.periods.add(periodsItem);
    return this;
  }

  /**
   * Per-bucket sample size and completeness: mentions is the total the shares were computed on (1-3 mentions produce the 100/50/33.33 low-sample patterns); partial marks buckets still collecting data or clipped by the requested window.
   * @return periods
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERIODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SovResponsePeriodsInner> getPeriods() {
    return periods;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriods(@javax.annotation.Nullable List<SovResponsePeriodsInner> periods) {
    this.periods = periods;
  }


  public SovResponse overTime(@javax.annotation.Nullable List<SovResponseOverTimeInner> overTime) {
    this.overTime = overTime;
    return this;
  }

  public SovResponse addOverTimeItem(SovResponseOverTimeInner overTimeItem) {
    if (this.overTime == null) {
      this.overTime = new ArrayList<>();
    }
    this.overTime.add(overTimeItem);
    return this;
  }

  /**
   * Get overTime
   * @return overTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OVER_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SovResponseOverTimeInner> getOverTime() {
    return overTime;
  }


  @JsonProperty(value = JSON_PROPERTY_OVER_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverTime(@javax.annotation.Nullable List<SovResponseOverTimeInner> overTime) {
    this.overTime = overTime;
  }


  public SovResponse current(@javax.annotation.Nullable List<SovResponseCurrentInner> current) {
    this.current = current;
    return this;
  }

  public SovResponse addCurrentItem(SovResponseCurrentInner currentItem) {
    if (this.current == null) {
      this.current = new ArrayList<>();
    }
    this.current.add(currentItem);
    return this;
  }

  /**
   * Get current
   * @return current
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SovResponseCurrentInner> getCurrent() {
    return current;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrent(@javax.annotation.Nullable List<SovResponseCurrentInner> current) {
    this.current = current;
  }


  public SovResponse breakdown(@javax.annotation.Nullable List<SovResponseBreakdownInner> breakdown) {
    this.breakdown = breakdown;
    return this;
  }

  public SovResponse addBreakdownItem(SovResponseBreakdownInner breakdownItem) {
    if (this.breakdown == null) {
      this.breakdown = new ArrayList<>();
    }
    this.breakdown.add(breakdownItem);
    return this;
  }

  /**
   * Get breakdown
   * @return breakdown
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SovResponseBreakdownInner> getBreakdown() {
    return breakdown;
  }


  @JsonProperty(value = JSON_PROPERTY_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakdown(@javax.annotation.Nullable List<SovResponseBreakdownInner> breakdown) {
    this.breakdown = breakdown;
  }


  public SovResponse others(@javax.annotation.Nullable List<Object> others) {
    this.others = others;
    return this;
  }

  public SovResponse addOthersItem(Object othersItem) {
    if (this.others == null) {
      this.others = new ArrayList<>();
    }
    this.others.add(othersItem);
    return this;
  }

  /**
   * Get others
   * @return others
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OTHERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Object> getOthers() {
    return others;
  }


  @JsonProperty(value = JSON_PROPERTY_OTHERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOthers(@javax.annotation.Nullable List<Object> others) {
    this.others = others;
  }


  /**
   * Return true if this SovResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SovResponse sovResponse = (SovResponse) o;
    return Objects.equals(this.projectId, sovResponse.projectId) &&
        Objects.equals(this.periods, sovResponse.periods) &&
        Objects.equals(this.overTime, sovResponse.overTime) &&
        Objects.equals(this.current, sovResponse.current) &&
        Objects.equals(this.breakdown, sovResponse.breakdown) &&
        Objects.equals(this.others, sovResponse.others);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, periods, overTime, current, breakdown, others);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SovResponse {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    periods: ").append(toIndentedString(periods)).append("\n");
    sb.append("    overTime: ").append(toIndentedString(overTime)).append("\n");
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("    others: ").append(toIndentedString(others)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `periods` to the URL query string
    if (getPeriods() != null) {
      for (int i = 0; i < getPeriods().size(); i++) {
        if (getPeriods().get(i) != null) {
          joiner.add(getPeriods().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%speriods%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `over_time` to the URL query string
    if (getOverTime() != null) {
      for (int i = 0; i < getOverTime().size(); i++) {
        if (getOverTime().get(i) != null) {
          joiner.add(getOverTime().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sover_time%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `current` to the URL query string
    if (getCurrent() != null) {
      for (int i = 0; i < getCurrent().size(); i++) {
        if (getCurrent().get(i) != null) {
          joiner.add(getCurrent().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scurrent%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `breakdown` to the URL query string
    if (getBreakdown() != null) {
      for (int i = 0; i < getBreakdown().size(); i++) {
        if (getBreakdown().get(i) != null) {
          joiner.add(getBreakdown().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sbreakdown%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `others` to the URL query string
    if (getOthers() != null) {
      for (int i = 0; i < getOthers().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sothers%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getOthers().get(i)))));
      }
    }

    return joiner.toString();
  }
}

