/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.Actor;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * SovResponseOthersInner
 */
@JsonPropertyOrder({
  SovResponseOthersInner.JSON_PROPERTY_RANK,
  SovResponseOthersInner.JSON_PROPERTY_ACTOR,
  SovResponseOthersInner.JSON_PROPERTY_SHARE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SovResponseOthersInner {
  public static final String JSON_PROPERTY_RANK = "rank";
  @javax.annotation.Nullable
  private Integer rank;

  public static final String JSON_PROPERTY_ACTOR = "actor";
  @javax.annotation.Nullable
  private Actor actor;

  public static final String JSON_PROPERTY_SHARE = "share";
  @javax.annotation.Nullable
  private BigDecimal share;

  public SovResponseOthersInner() { 
  }

  public SovResponseOthersInner rank(@javax.annotation.Nullable Integer rank) {
    this.rank = rank;
    return this;
  }

  /**
   * Get rank
   * @return rank
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRank() {
    return rank;
  }


  @JsonProperty(value = JSON_PROPERTY_RANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRank(@javax.annotation.Nullable Integer rank) {
    this.rank = rank;
  }


  public SovResponseOthersInner actor(@javax.annotation.Nullable Actor actor) {
    this.actor = actor;
    return this;
  }

  /**
   * Get actor
   * @return actor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Actor getActor() {
    return actor;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActor(@javax.annotation.Nullable Actor actor) {
    this.actor = actor;
  }


  public SovResponseOthersInner share(@javax.annotation.Nullable BigDecimal share) {
    this.share = share;
    return this;
  }

  /**
   * Get share
   * @return share
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHARE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getShare() {
    return share;
  }


  @JsonProperty(value = JSON_PROPERTY_SHARE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShare(@javax.annotation.Nullable BigDecimal share) {
    this.share = share;
  }


  /**
   * Return true if this SovResponse_others_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SovResponseOthersInner sovResponseOthersInner = (SovResponseOthersInner) o;
    return Objects.equals(this.rank, sovResponseOthersInner.rank) &&
        Objects.equals(this.actor, sovResponseOthersInner.actor) &&
        Objects.equals(this.share, sovResponseOthersInner.share);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rank, actor, share);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SovResponseOthersInner {\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    share: ").append(toIndentedString(share)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `rank` to the URL query string
    if (getRank() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srank%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRank()))));
    }

    // add `actor` to the URL query string
    if (getActor() != null) {
      joiner.add(getActor().toUrlQueryString(prefix + "actor" + suffix));
    }

    // add `share` to the URL query string
    if (getShare() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshare%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShare()))));
    }

    return joiner.toString();
  }
}

