/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * The live project the store maps to: its domain equals the store&#39;s, or is a parent or subdomain of it. Null when no project matches
 */
@JsonPropertyOrder({
  StoreConnectionResponseProject.JSON_PROPERTY_ID,
  StoreConnectionResponseProject.JSON_PROPERTY_NAME,
  StoreConnectionResponseProject.JSON_PROPERTY_DOMAIN,
  StoreConnectionResponseProject.JSON_PROPERTY_COUNTRY_CODE,
  StoreConnectionResponseProject.JSON_PROPERTY_LANGUAGE_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class StoreConnectionResponseProject {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nonnull
  private String domain;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  private JsonNullable<String> countryCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LANGUAGE_CODE = "language_code";
  private JsonNullable<String> languageCode = JsonNullable.<String>undefined();

  public StoreConnectionResponseProject() { 
  }

  public StoreConnectionResponseProject id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public StoreConnectionResponseProject name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public StoreConnectionResponseProject domain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
  }


  public StoreConnectionResponseProject countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = JsonNullable.<String>of(countryCode);
    return this;
  }

  /**
   * Get countryCode
   * @return countryCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCountryCode() {
        return countryCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COUNTRY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCountryCode_JsonNullable() {
    return countryCode;
  }
  
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  public void setCountryCode_JsonNullable(JsonNullable<String> countryCode) {
    this.countryCode = countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = JsonNullable.<String>of(countryCode);
  }


  public StoreConnectionResponseProject languageCode(@javax.annotation.Nullable String languageCode) {
    this.languageCode = JsonNullable.<String>of(languageCode);
    return this;
  }

  /**
   * Get languageCode
   * @return languageCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLanguageCode() {
        return languageCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LANGUAGE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLanguageCode_JsonNullable() {
    return languageCode;
  }
  
  @JsonProperty(JSON_PROPERTY_LANGUAGE_CODE)
  public void setLanguageCode_JsonNullable(JsonNullable<String> languageCode) {
    this.languageCode = languageCode;
  }

  public void setLanguageCode(@javax.annotation.Nullable String languageCode) {
    this.languageCode = JsonNullable.<String>of(languageCode);
  }


  /**
   * Return true if this StoreConnectionResponse_project object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreConnectionResponseProject storeConnectionResponseProject = (StoreConnectionResponseProject) o;
    return Objects.equals(this.id, storeConnectionResponseProject.id) &&
        Objects.equals(this.name, storeConnectionResponseProject.name) &&
        Objects.equals(this.domain, storeConnectionResponseProject.domain) &&
        equalsNullable(this.countryCode, storeConnectionResponseProject.countryCode) &&
        equalsNullable(this.languageCode, storeConnectionResponseProject.languageCode);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, domain, hashCodeNullable(countryCode), hashCodeNullable(languageCode));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreConnectionResponseProject {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `country_code` to the URL query string
    if (getCountryCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scountry_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountryCode()))));
    }

    // add `language_code` to the URL query string
    if (getLanguageCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slanguage_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLanguageCode()))));
    }

    return joiner.toString();
  }
}

