/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * TechnicalGeoReportContentRevertRequest
 */
@JsonPropertyOrder({
  TechnicalGeoReportContentRevertRequest.JSON_PROPERTY_PROJECT_ID,
  TechnicalGeoReportContentRevertRequest.JSON_PROPERTY_REPORT_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class TechnicalGeoReportContentRevertRequest {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @javax.annotation.Nonnull
  private Integer projectId;

  /**
   * Only llms_txt reports have editable content
   */
  public enum ReportTypeEnum {
    LLMS_TXT(String.valueOf("llms_txt"));

    private String value;

    ReportTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReportTypeEnum fromValue(String value) {
      for (ReportTypeEnum b : ReportTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REPORT_TYPE = "report_type";
  @javax.annotation.Nonnull
  private ReportTypeEnum reportType;

  public TechnicalGeoReportContentRevertRequest() { 
  }

  public TechnicalGeoReportContentRevertRequest projectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@javax.annotation.Nonnull Integer projectId) {
    this.projectId = projectId;
  }


  public TechnicalGeoReportContentRevertRequest reportType(@javax.annotation.Nonnull ReportTypeEnum reportType) {
    this.reportType = reportType;
    return this;
  }

  /**
   * Only llms_txt reports have editable content
   * @return reportType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REPORT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ReportTypeEnum getReportType() {
    return reportType;
  }


  @JsonProperty(value = JSON_PROPERTY_REPORT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReportType(@javax.annotation.Nonnull ReportTypeEnum reportType) {
    this.reportType = reportType;
  }


  /**
   * Return true if this TechnicalGeoReportContentRevertRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechnicalGeoReportContentRevertRequest technicalGeoReportContentRevertRequest = (TechnicalGeoReportContentRevertRequest) o;
    return Objects.equals(this.projectId, technicalGeoReportContentRevertRequest.projectId) &&
        Objects.equals(this.reportType, technicalGeoReportContentRevertRequest.reportType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, reportType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechnicalGeoReportContentRevertRequest {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `report_type` to the URL query string
    if (getReportType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreport_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReportType()))));
    }

    return joiner.toString();
  }
}

