/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.llmpulse.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.llmpulse.sdk.model.Actor;
import ai.llmpulse.sdk.model.TimeseriesPoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.llmpulse.sdk.ApiClient;
/**
 * TimeseriesSeries
 */
@JsonPropertyOrder({
  TimeseriesSeries.JSON_PROPERTY_ACTOR,
  TimeseriesSeries.JSON_PROPERTY_METRIC,
  TimeseriesSeries.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class TimeseriesSeries {
  public static final String JSON_PROPERTY_ACTOR = "actor";
  @javax.annotation.Nullable
  private Actor actor;

  public static final String JSON_PROPERTY_METRIC = "metric";
  @javax.annotation.Nullable
  private String metric;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<TimeseriesPoint> data = new ArrayList<>();

  public TimeseriesSeries() { 
  }

  public TimeseriesSeries actor(@javax.annotation.Nullable Actor actor) {
    this.actor = actor;
    return this;
  }

  /**
   * Get actor
   * @return actor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Actor getActor() {
    return actor;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActor(@javax.annotation.Nullable Actor actor) {
    this.actor = actor;
  }


  public TimeseriesSeries metric(@javax.annotation.Nullable String metric) {
    this.metric = metric;
    return this;
  }

  /**
   * Get metric
   * @return metric
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METRIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMetric() {
    return metric;
  }


  @JsonProperty(value = JSON_PROPERTY_METRIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetric(@javax.annotation.Nullable String metric) {
    this.metric = metric;
  }


  public TimeseriesSeries data(@javax.annotation.Nullable List<TimeseriesPoint> data) {
    this.data = data;
    return this;
  }

  public TimeseriesSeries addDataItem(TimeseriesPoint dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<TimeseriesPoint> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<TimeseriesPoint> data) {
    this.data = data;
  }


  /**
   * Return true if this TimeseriesSeries object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeseriesSeries timeseriesSeries = (TimeseriesSeries) o;
    return Objects.equals(this.actor, timeseriesSeries.actor) &&
        Objects.equals(this.metric, timeseriesSeries.metric) &&
        Objects.equals(this.data, timeseriesSeries.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actor, metric, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeseriesSeries {\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    metric: ").append(toIndentedString(metric)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `actor` to the URL query string
    if (getActor() != null) {
      joiner.add(getActor().toUrlQueryString(prefix + "actor" + suffix));
    }

    // add `metric` to the URL query string
    if (getMetric() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetric%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetric()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (int i = 0; i < getData().size(); i++) {
        if (getData().get(i) != null) {
          joiner.add(getData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

