/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ai.llmpulse.sdk.api;

import ai.llmpulse.sdk.ApiClient;
import ai.llmpulse.sdk.ApiException;
import ai.llmpulse.sdk.ApiResponse;
import ai.llmpulse.sdk.Configuration;
import ai.llmpulse.sdk.Pair;

import ai.llmpulse.sdk.model.ApiError;
import java.time.OffsetDateTime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CitationIntelligenceApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public CitationIntelligenceApi() {
    this(Configuration.getDefaultApiClient());
  }

  public CitationIntelligenceApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Cited URL cached content
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @throws ApiException if fails to make API call
   */
  public void getCitedUrlContent(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256) throws ApiException {
    getCitedUrlContent(projectId, urlSha256, null);
  }

  /**
   * Cited URL cached content
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void getCitedUrlContent(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, Map<String, String> headers) throws ApiException {
    getCitedUrlContentWithHttpInfo(projectId, urlSha256, headers);
  }

  /**
   * Cited URL cached content
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> getCitedUrlContentWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256) throws ApiException {
    return getCitedUrlContentWithHttpInfo(projectId, urlSha256, null);
  }

  /**
   * Cited URL cached content
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> getCitedUrlContentWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCitedUrlContentRequestBuilder(projectId, urlSha256, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCitedUrlContent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCitedUrlContentRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling getCitedUrlContent");
    }
    // verify the required parameter 'urlSha256' is set
    if (urlSha256 == null) {
      throw new ApiException(400, "Missing the required parameter 'urlSha256' when calling getCitedUrlContent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/citation_intelligence/urls/{url_sha256}/content"
        .replace("{url_sha256}", ApiClient.urlEncode(urlSha256.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Cited URL detail
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @throws ApiException if fails to make API call
   */
  public void getCitedUrlDetail(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256) throws ApiException {
    getCitedUrlDetail(projectId, urlSha256, null);
  }

  /**
   * Cited URL detail
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void getCitedUrlDetail(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, Map<String, String> headers) throws ApiException {
    getCitedUrlDetailWithHttpInfo(projectId, urlSha256, headers);
  }

  /**
   * Cited URL detail
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> getCitedUrlDetailWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256) throws ApiException {
    return getCitedUrlDetailWithHttpInfo(projectId, urlSha256, null);
  }

  /**
   * Cited URL detail
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> getCitedUrlDetailWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCitedUrlDetailRequestBuilder(projectId, urlSha256, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCitedUrlDetail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCitedUrlDetailRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling getCitedUrlDetail");
    }
    // verify the required parameter 'urlSha256' is set
    if (urlSha256 == null) {
      throw new ApiException(400, "Missing the required parameter 'urlSha256' when calling getCitedUrlDetail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/citation_intelligence/urls/{url_sha256}"
        .replace("{url_sha256}", ApiClient.urlEncode(urlSha256.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Mention share by citing domain
   * For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.
   * @param projectId Project ID (required)
   * @param domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @throws ApiException if fails to make API call
   */
  public void getMentionsByCitingDomain(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull List<String> domains, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to) throws ApiException {
    getMentionsByCitingDomain(projectId, domains, model, collectionId, countryCode, languageCode, prompt, from, to, null);
  }

  /**
   * Mention share by citing domain
   * For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.
   * @param projectId Project ID (required)
   * @param domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void getMentionsByCitingDomain(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull List<String> domains, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, Map<String, String> headers) throws ApiException {
    getMentionsByCitingDomainWithHttpInfo(projectId, domains, model, collectionId, countryCode, languageCode, prompt, from, to, headers);
  }

  /**
   * Mention share by citing domain
   * For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.
   * @param projectId Project ID (required)
   * @param domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> getMentionsByCitingDomainWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull List<String> domains, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to) throws ApiException {
    return getMentionsByCitingDomainWithHttpInfo(projectId, domains, model, collectionId, countryCode, languageCode, prompt, from, to, null);
  }

  /**
   * Mention share by citing domain
   * For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.
   * @param projectId Project ID (required)
   * @param domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> getMentionsByCitingDomainWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull List<String> domains, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMentionsByCitingDomainRequestBuilder(projectId, domains, model, collectionId, countryCode, languageCode, prompt, from, to, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMentionsByCitingDomain", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMentionsByCitingDomainRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull List<String> domains, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling getMentionsByCitingDomain");
    }
    // verify the required parameter 'domains' is set
    if (domains == null) {
      throw new ApiException(400, "Missing the required parameter 'domains' when calling getMentionsByCitingDomain");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/citation_intelligence/mentions_by_domain";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));
    localVarQueryParameterBaseName = "domains";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "domains", domains));
    localVarQueryParameterBaseName = "model";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("model", model));
    localVarQueryParameterBaseName = "collection_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("collection_id", collectionId));
    localVarQueryParameterBaseName = "country_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("country_code", countryCode));
    localVarQueryParameterBaseName = "language_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("language_code", languageCode));
    localVarQueryParameterBaseName = "prompt";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prompt", prompt));
    localVarQueryParameterBaseName = "from";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("from", from));
    localVarQueryParameterBaseName = "to";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("to", to));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Grouped citation intelligence
   * Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position&#x3D;0. Owned and competitor source matching honor the project&#39;s exact-subdomain setting. Filter vocabulary aligns with &#x60;source_type&#x60; returned by the API.
   * @param projectId Project ID (required)
   * @param view  (optional, default to url)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param order  (optional)
   * @param direction  (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @param query  (optional)
   * @param sourceType  (optional)
   * @param sentiment  (optional)
   * @param contentGap  (optional)
   * @throws ApiException if fails to make API call
   */
  public void listCitationGroups(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable String view, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String query, @javax.annotation.Nullable String sourceType, @javax.annotation.Nullable String sentiment, @javax.annotation.Nullable String contentGap) throws ApiException {
    listCitationGroups(projectId, view, page, perPage, order, direction, model, collectionId, countryCode, languageCode, prompt, from, to, query, sourceType, sentiment, contentGap, null);
  }

  /**
   * Grouped citation intelligence
   * Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position&#x3D;0. Owned and competitor source matching honor the project&#39;s exact-subdomain setting. Filter vocabulary aligns with &#x60;source_type&#x60; returned by the API.
   * @param projectId Project ID (required)
   * @param view  (optional, default to url)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param order  (optional)
   * @param direction  (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @param query  (optional)
   * @param sourceType  (optional)
   * @param sentiment  (optional)
   * @param contentGap  (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void listCitationGroups(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable String view, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String query, @javax.annotation.Nullable String sourceType, @javax.annotation.Nullable String sentiment, @javax.annotation.Nullable String contentGap, Map<String, String> headers) throws ApiException {
    listCitationGroupsWithHttpInfo(projectId, view, page, perPage, order, direction, model, collectionId, countryCode, languageCode, prompt, from, to, query, sourceType, sentiment, contentGap, headers);
  }

  /**
   * Grouped citation intelligence
   * Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position&#x3D;0. Owned and competitor source matching honor the project&#39;s exact-subdomain setting. Filter vocabulary aligns with &#x60;source_type&#x60; returned by the API.
   * @param projectId Project ID (required)
   * @param view  (optional, default to url)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param order  (optional)
   * @param direction  (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @param query  (optional)
   * @param sourceType  (optional)
   * @param sentiment  (optional)
   * @param contentGap  (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listCitationGroupsWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable String view, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String query, @javax.annotation.Nullable String sourceType, @javax.annotation.Nullable String sentiment, @javax.annotation.Nullable String contentGap) throws ApiException {
    return listCitationGroupsWithHttpInfo(projectId, view, page, perPage, order, direction, model, collectionId, countryCode, languageCode, prompt, from, to, query, sourceType, sentiment, contentGap, null);
  }

  /**
   * Grouped citation intelligence
   * Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position&#x3D;0. Owned and competitor source matching honor the project&#39;s exact-subdomain setting. Filter vocabulary aligns with &#x60;source_type&#x60; returned by the API.
   * @param projectId Project ID (required)
   * @param view  (optional, default to url)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param order  (optional)
   * @param direction  (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId  (optional)
   * @param countryCode ISO country code (e.g. US, GB, DE) (optional)
   * @param languageCode ISO language code (e.g. en, es, de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param from  (optional)
   * @param to  (optional)
   * @param query  (optional)
   * @param sourceType  (optional)
   * @param sentiment  (optional)
   * @param contentGap  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listCitationGroupsWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable String view, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String query, @javax.annotation.Nullable String sourceType, @javax.annotation.Nullable String sentiment, @javax.annotation.Nullable String contentGap, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listCitationGroupsRequestBuilder(projectId, view, page, perPage, order, direction, model, collectionId, countryCode, languageCode, prompt, from, to, query, sourceType, sentiment, contentGap, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listCitationGroups", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listCitationGroupsRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable String view, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String model, @javax.annotation.Nullable Integer collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String query, @javax.annotation.Nullable String sourceType, @javax.annotation.Nullable String sentiment, @javax.annotation.Nullable String contentGap, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling listCitationGroups");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/citation_intelligence/groups";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));
    localVarQueryParameterBaseName = "view";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("view", view));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "per_page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("per_page", perPage));
    localVarQueryParameterBaseName = "order";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("order", order));
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "model";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("model", model));
    localVarQueryParameterBaseName = "collection_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("collection_id", collectionId));
    localVarQueryParameterBaseName = "country_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("country_code", countryCode));
    localVarQueryParameterBaseName = "language_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("language_code", languageCode));
    localVarQueryParameterBaseName = "prompt";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prompt", prompt));
    localVarQueryParameterBaseName = "from";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("from", from));
    localVarQueryParameterBaseName = "to";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("to", to));
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "source_type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("source_type", sourceType));
    localVarQueryParameterBaseName = "sentiment";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sentiment", sentiment));
    localVarQueryParameterBaseName = "content_gap";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("content_gap", contentGap));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Cited URL occurrences
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @throws ApiException if fails to make API call
   */
  public void listCitedUrlOccurrences(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage) throws ApiException {
    listCitedUrlOccurrences(projectId, urlSha256, page, perPage, null);
  }

  /**
   * Cited URL occurrences
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void listCitedUrlOccurrences(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, Map<String, String> headers) throws ApiException {
    listCitedUrlOccurrencesWithHttpInfo(projectId, urlSha256, page, perPage, headers);
  }

  /**
   * Cited URL occurrences
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listCitedUrlOccurrencesWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage) throws ApiException {
    return listCitedUrlOccurrencesWithHttpInfo(projectId, urlSha256, page, perPage, null);
  }

  /**
   * Cited URL occurrences
   * 
   * @param projectId Project ID (required)
   * @param urlSha256 64-character hex SHA-256 of the cited URL (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listCitedUrlOccurrencesWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listCitedUrlOccurrencesRequestBuilder(projectId, urlSha256, page, perPage, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listCitedUrlOccurrences", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listCitedUrlOccurrencesRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nonnull String urlSha256, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling listCitedUrlOccurrences");
    }
    // verify the required parameter 'urlSha256' is set
    if (urlSha256 == null) {
      throw new ApiException(400, "Missing the required parameter 'urlSha256' when calling listCitedUrlOccurrences");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/citation_intelligence/urls/{url_sha256}/occurrences"
        .replace("{url_sha256}", ApiClient.urlEncode(urlSha256.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "per_page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("per_page", perPage));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
