/*
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ai.llmpulse.sdk.api;

import ai.llmpulse.sdk.ApiClient;
import ai.llmpulse.sdk.ApiException;
import ai.llmpulse.sdk.ApiResponse;
import ai.llmpulse.sdk.Configuration;
import ai.llmpulse.sdk.Pair;

import ai.llmpulse.sdk.model.ApiError;
import java.time.OffsetDateTime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ShoppingAdsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public ShoppingAdsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ShoppingAdsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * List AI ad placements
   * Paid placements returned inside AI answers. view&#x3D;advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view&#x3D;ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per advertising domain, or one per placement (optional, default to advertisers)
   * @param owned Return only placements identified as the tracked brand&#39;s own (view&#x3D;ads) (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction Sort direction for view&#x3D;advertisers. Defaults to desc, except avg_position and domain which default to asc. (optional)
   * @param query Case-insensitive substring filter on the ad title, domain or snippet (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @throws ApiException if fails to make API call
   */
  public void listAds(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output) throws ApiException {
    listAds(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, null);
  }

  /**
   * List AI ad placements
   * Paid placements returned inside AI answers. view&#x3D;advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view&#x3D;ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per advertising domain, or one per placement (optional, default to advertisers)
   * @param owned Return only placements identified as the tracked brand&#39;s own (view&#x3D;ads) (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction Sort direction for view&#x3D;advertisers. Defaults to desc, except avg_position and domain which default to asc. (optional)
   * @param query Case-insensitive substring filter on the ad title, domain or snippet (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void listAds(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output, Map<String, String> headers) throws ApiException {
    listAdsWithHttpInfo(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, headers);
  }

  /**
   * List AI ad placements
   * Paid placements returned inside AI answers. view&#x3D;advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view&#x3D;ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per advertising domain, or one per placement (optional, default to advertisers)
   * @param owned Return only placements identified as the tracked brand&#39;s own (view&#x3D;ads) (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction Sort direction for view&#x3D;advertisers. Defaults to desc, except avg_position and domain which default to asc. (optional)
   * @param query Case-insensitive substring filter on the ad title, domain or snippet (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listAdsWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output) throws ApiException {
    return listAdsWithHttpInfo(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, null);
  }

  /**
   * List AI ad placements
   * Paid placements returned inside AI answers. view&#x3D;advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view&#x3D;ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per advertising domain, or one per placement (optional, default to advertisers)
   * @param owned Return only placements identified as the tracked brand&#39;s own (view&#x3D;ads) (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction Sort direction for view&#x3D;advertisers. Defaults to desc, except avg_position and domain which default to asc. (optional)
   * @param query Case-insensitive substring filter on the ad title, domain or snippet (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listAdsWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAdsRequestBuilder(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAds", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAdsRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling listAds");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dimensions/ads";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "per_page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("per_page", perPage));
    localVarQueryParameterBaseName = "view";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("view", view));
    localVarQueryParameterBaseName = "owned";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("owned", owned));
    localVarQueryParameterBaseName = "order";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("order", order));
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "model";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("model", model));
    localVarQueryParameterBaseName = "collection_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("collection_id", collectionId));
    localVarQueryParameterBaseName = "country_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("country_code", countryCode));
    localVarQueryParameterBaseName = "language_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("language_code", languageCode));
    localVarQueryParameterBaseName = "prompt";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prompt", prompt));
    localVarQueryParameterBaseName = "prompt_type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prompt_type", promptType));
    localVarQueryParameterBaseName = "brand_kind";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("brand_kind", brandKind));
    localVarQueryParameterBaseName = "range";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("range", range));
    localVarQueryParameterBaseName = "from";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("from", from));
    localVarQueryParameterBaseName = "to";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("to", to));
    localVarQueryParameterBaseName = "output";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("output", output));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List shopping results
   * Product cards returned inside AI answers. view&#x3D;products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view&#x3D;merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per distinct product, or one per merchant (optional, default to products)
   * @param owned Return only products identified as the tracked brand&#39;s own. On view&#x3D;merchants this narrows to the merchants selling those products; the totals block stays account-wide. (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction  (optional, default to desc)
   * @param query Case-insensitive substring filter on the product title (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @throws ApiException if fails to make API call
   */
  public void listShopping(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output) throws ApiException {
    listShopping(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, null);
  }

  /**
   * List shopping results
   * Product cards returned inside AI answers. view&#x3D;products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view&#x3D;merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per distinct product, or one per merchant (optional, default to products)
   * @param owned Return only products identified as the tracked brand&#39;s own. On view&#x3D;merchants this narrows to the merchants selling those products; the totals block stays account-wide. (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction  (optional, default to desc)
   * @param query Case-insensitive substring filter on the product title (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void listShopping(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output, Map<String, String> headers) throws ApiException {
    listShoppingWithHttpInfo(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, headers);
  }

  /**
   * List shopping results
   * Product cards returned inside AI answers. view&#x3D;products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view&#x3D;merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per distinct product, or one per merchant (optional, default to products)
   * @param owned Return only products identified as the tracked brand&#39;s own. On view&#x3D;merchants this narrows to the merchants selling those products; the totals block stays account-wide. (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction  (optional, default to desc)
   * @param query Case-insensitive substring filter on the product title (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listShoppingWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output) throws ApiException {
    return listShoppingWithHttpInfo(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, null);
  }

  /**
   * List shopping results
   * Product cards returned inside AI answers. view&#x3D;products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view&#x3D;merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.
   * @param projectId Project ID (required)
   * @param page  (optional, default to 1)
   * @param perPage  (optional, default to 20)
   * @param view Row shape: one per distinct product, or one per merchant (optional, default to products)
   * @param owned Return only products identified as the tracked brand&#39;s own. On view&#x3D;merchants this narrows to the merchants selling those products; the totals block stays account-wide. (optional)
   * @param order Sort field; the allowed set depends on view (optional)
   * @param direction  (optional, default to desc)
   * @param query Case-insensitive substring filter on the product title (optional)
   * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
   * @param collectionId One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize. (optional)
   * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
   * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
   * @param prompt Filter by prompt ID (optional)
   * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
   * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
   * @param range Number of days to look back (alternative to from/to) (optional)
   * @param from  (optional)
   * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
   * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> listShoppingWithHttpInfo(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listShoppingRequestBuilder(projectId, page, perPage, view, owned, order, direction, query, model, collectionId, countryCode, languageCode, prompt, promptType, brandKind, range, from, to, output, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listShopping", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listShoppingRequestBuilder(@javax.annotation.Nonnull Integer projectId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String view, @javax.annotation.Nullable Boolean owned, @javax.annotation.Nullable String order, @javax.annotation.Nullable String direction, @javax.annotation.Nullable String query, @javax.annotation.Nullable String model, @javax.annotation.Nullable String collectionId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String languageCode, @javax.annotation.Nullable Integer prompt, @javax.annotation.Nullable String promptType, @javax.annotation.Nullable String brandKind, @javax.annotation.Nullable Integer range, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, @javax.annotation.Nullable String output, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling listShopping");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dimensions/shopping";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "project_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("project_id", projectId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "per_page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("per_page", perPage));
    localVarQueryParameterBaseName = "view";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("view", view));
    localVarQueryParameterBaseName = "owned";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("owned", owned));
    localVarQueryParameterBaseName = "order";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("order", order));
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "model";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("model", model));
    localVarQueryParameterBaseName = "collection_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("collection_id", collectionId));
    localVarQueryParameterBaseName = "country_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("country_code", countryCode));
    localVarQueryParameterBaseName = "language_code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("language_code", languageCode));
    localVarQueryParameterBaseName = "prompt";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prompt", prompt));
    localVarQueryParameterBaseName = "prompt_type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prompt_type", promptType));
    localVarQueryParameterBaseName = "brand_kind";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("brand_kind", brandKind));
    localVarQueryParameterBaseName = "range";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("range", range));
    localVarQueryParameterBaseName = "from";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("from", from));
    localVarQueryParameterBaseName = "to";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("to", to));
    localVarQueryParameterBaseName = "output";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("output", output));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
